### ISSUE TITLE
[BUG]./qubinode-installer -p ocp4 -d do not remove instances

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#109]
**Qubinode Version**  
Qubinode releasev2.2

**Describe the bug**
Running ./qubinode-installer -p ocp4 -d, it seem it do not remove the master and compute nodes

**Expected behavior**
Expect the script should be shutdown and delete the KVM instances

**Screenshots**

Output log:

`Loading function qubinode_required_prereqs

 [WARNING]: While constructing a mapping from /home/louie/qubinode-installer/playbooks/vars/all.yml, line 7, column 1, found a duplicate dict key
(host_device). Using last defined value only.

 [WARNING]: While constructing a mapping from /home/louie/qubinode-installer/playbooks/vars/all.yml, line 7, column 1, found a duplicate dict key
(vg_name). Using last defined value only.

 [WARNING]: While constructing a mapping from /home/louie/qubinode-installer/playbooks/vars/all.yml, line 7, column 1, found a duplicate dict key
(qubinode_bridge_name). Using last defined value only.

PLAY [create nodes dns records on IDM server] ********************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
Tuesday 07 January 2020  01:01:47 +0800 (0:00:00.106)       0:00:00.106 ******* 
ok: [localhost]

TASK [fail] ******************************************************************************************************************************************
Tuesday 07 January 2020  01:01:49 +0800 (0:00:01.587)       0:00:01.694 ******* 
skipping: [localhost]

TASK [set dns record state] **************************************************************************************************************************
Tuesday 07 January 2020  01:01:49 +0800 (0:00:00.133)       0:00:01.827 ******* 
ok: [localhost]

TASK [add bootstrap to dns forward zone] *************************************************************************************************************
Tuesday 07 January 2020  01:01:49 +0800 (0:00:00.142)       0:00:01.970 ******* 
ok: [localhost]

TASK [add bootstrap to reverse forward zone] *********************************************************************************************************
Tuesday 07 January 2020  01:01:49 +0800 (0:00:00.157)       0:00:02.127 ******* 
ok: [localhost]

TASK [add api-int to dns records list] ***************************************************************************************************************
Tuesday 07 January 2020  01:01:49 +0800 (0:00:00.151)       0:00:02.279 ******* 
ok: [localhost]

TASK [add api to dns records list] *******************************************************************************************************************
Tuesday 07 January 2020  01:01:50 +0800 (0:00:00.154)       0:00:02.434 ******* 
ok: [localhost]

TASK [set  master nodes forward zone records] ********************************************************************************************************
Tuesday 07 January 2020  01:01:50 +0800 (0:00:00.140)       0:00:02.575 ******* 
ok: [localhost] => (item=0)
ok: [localhost] => (item=1)
ok: [localhost] => (item=2)

TASK [set  master nodes reverse zone records] ********************************************************************************************************
Tuesday 07 January 2020  01:01:50 +0800 (0:00:00.276)       0:00:02.852 ******* 
ok: [localhost] => (item=0)
ok: [localhost] => (item=1)
ok: [localhost] => (item=2)

TASK [set etcd nodes forward zone records] ***********************************************************************************************************
Tuesday 07 January 2020  01:01:50 +0800 (0:00:00.219)       0:00:03.072 ******* 
ok: [localhost] => (item=0)
ok: [localhost] => (item=1)
ok: [localhost] => (item=2)

TASK [set compute nodes forward zone records] ********************************************************************************************************
Tuesday 07 January 2020  01:01:50 +0800 (0:00:00.222)       0:00:03.294 ******* 
ok: [localhost] => (item=0)
ok: [localhost] => (item=1)

TASK [set compute nodes reverse zone records] ********************************************************************************************************
Tuesday 07 January 2020  01:01:51 +0800 (0:00:00.204)       0:00:03.499 ******* 
ok: [localhost] => (item=0)
ok: [localhost] => (item=1)

TASK [create forward dns zone lab.home] **************************************************************************************************************
Tuesday 07 January 2020  01:01:51 +0800 (0:00:00.193)       0:00:03.693 ******* 
ok: [localhost]

TASK [create reverse dns zone 50.168.192.in-addr.arpa.] **********************************************************************************************
Tuesday 07 January 2020  01:01:52 +0800 (0:00:00.773)       0:00:04.466 ******* 
ok: [localhost]

TASK [Create/Delete A Records] ***********************************************************************************************************************
Tuesday 07 January 2020  01:01:52 +0800 (0:00:00.602)       0:00:05.068 ******* 
ok: [localhost] => (item={'ptr_record': 2, 'hostname': u'bootstrap', 'ipaddr': u'192.168.50.2'})
ok: [localhost] => (item={'ptr_record': 1, 'hostname': u'api-int', 'ipaddr': u'192.168.50.1'})
ok: [localhost] => (item={'ptr_record': 1, 'hostname': u'api', 'ipaddr': u'192.168.1.49'})
ok: [localhost] => (item={'ptr_record': u'10', 'hostname': u'master-0', 'ipaddr': u'192.168.50.10'})
ok: [localhost] => (item={'ptr_record': u'11', 'hostname': u'master-1', 'ipaddr': u'192.168.50.11'})
ok: [localhost] => (item={'ptr_record': u'12', 'hostname': u'master-2', 'ipaddr': u'192.168.50.12'})
ok: [localhost] => (item={'ptr_record': u'10', 'hostname': u'etcd-0', 'ipaddr': u'192.168.50.10'})
ok: [localhost] => (item={'ptr_record': u'11', 'hostname': u'etcd-1', 'ipaddr': u'192.168.50.11'})
ok: [localhost] => (item={'ptr_record': u'12', 'hostname': u'etcd-2', 'ipaddr': u'192.168.50.12'})
ok: [localhost] => (item={'ptr_record': u'13', 'hostname': u'compute-0', 'ipaddr': u'192.168.50.13'})
ok: [localhost] => (item={'ptr_record': u'14', 'hostname': u'compute-1', 'ipaddr': u'192.168.50.14'})

TASK [Create/Delete PTR Records] *********************************************************************************************************************
Tuesday 07 January 2020  01:01:58 +0800 (0:00:05.664)       0:00:10.733 ******* 
ok: [localhost] => (item={'ptr_record': 2, 'hostname': u'bootstrap', 'ipaddr': u'192.168.50.2'})
ok: [localhost] => (item={'ptr_record': u'10', 'hostname': u'master-0', 'ipaddr': u'192.168.50.10'})
ok: [localhost] => (item={'ptr_record': u'11', 'hostname': u'master-1', 'ipaddr': u'192.168.50.11'})
ok: [localhost] => (item={'ptr_record': u'12', 'hostname': u'master-2', 'ipaddr': u'192.168.50.12'})
ok: [localhost] => (item={'ptr_record': u'13', 'hostname': u'compute-0', 'ipaddr': u'192.168.50.13'})
ok: [localhost] => (item={'ptr_record': u'14', 'hostname': u'compute-1', 'ipaddr': u'192.168.50.14'})

TASK [Generate IPA Session Cookie] *******************************************************************************************************************
Tuesday 07 January 2020  01:02:01 +0800 (0:00:03.088)       0:00:13.821 ******* 
ok: [localhost]

TASK [Create Wildcard for Applications] **************************************************************************************************************
Tuesday 07 January 2020  01:02:02 +0800 (0:00:00.776)       0:00:14.598 ******* 
ok: [localhost]

TASK [Create Wildcard for Applications] **************************************************************************************************************
Tuesday 07 January 2020  01:02:02 +0800 (0:00:00.453)       0:00:15.051 ******* 
ok: [localhost]

TASK [Create SRV Records] ****************************************************************************************************************************
Tuesday 07 January 2020  01:02:03 +0800 (0:00:00.449)       0:00:15.501 ******* 
ok: [localhost] => (item=etcd-0)
ok: [localhost] => (item=etcd-1)
ok: [localhost] => (item=etcd-2)

PLAY RECAP *******************************************************************************************************************************************
localhost                  : ok=19   changed=0    unreachable=0    failed=0   

Tuesday 07 January 2020  01:02:04 +0800 (0:00:01.023)       0:00:16.525 ******* 
=============================================================================== 
Create/Delete A Records ----------------------------------------------------------------------------------------------------------------------- 5.66s
Create/Delete PTR Records --------------------------------------------------------------------------------------------------------------------- 3.09s
Gathering Facts ------------------------------------------------------------------------------------------------------------------------------- 1.59s
Create SRV Records ---------------------------------------------------------------------------------------------------------------------------- 1.02s
Generate IPA Session Cookie ------------------------------------------------------------------------------------------------------------------- 0.78s
create forward dns zone lab.home -------------------------------------------------------------------------------------------------------------- 0.77s
create reverse dns zone 50.168.192.in-addr.arpa. ---------------------------------------------------------------------------------------------- 0.60s
Create Wildcard for Applications -------------------------------------------------------------------------------------------------------------- 0.45s
Create Wildcard for Applications -------------------------------------------------------------------------------------------------------------- 0.45s
set  master nodes forward zone records -------------------------------------------------------------------------------------------------------- 0.28s
set etcd nodes forward zone records ----------------------------------------------------------------------------------------------------------- 0.22s
set  master nodes reverse zone records -------------------------------------------------------------------------------------------------------- 0.22s
set compute nodes forward zone records -------------------------------------------------------------------------------------------------------- 0.20s
set compute nodes reverse zone records -------------------------------------------------------------------------------------------------------- 0.19s
add bootstrap to dns forward zone ------------------------------------------------------------------------------------------------------------- 0.16s
add api-int to dns records list --------------------------------------------------------------------------------------------------------------- 0.15s
add bootstrap to reverse forward zone --------------------------------------------------------------------------------------------------------- 0.15s
set dns record state -------------------------------------------------------------------------------------------------------------------------- 0.14s
add api to dns records list ------------------------------------------------------------------------------------------------------------------- 0.14s
fail ------------------------------------------------------------------------------------------------------------------------------------------ 0.13s
Playbook run took 0 days, 0 hours, 0 minutes, 16 seconds
cat: rhcos-install/node-list: No such file or directory
Removing openshift-4-loadbalancer-ocp42 container.
c1424334e6157a2f7ec59c68e43000472f182b835d988f45ccbc88796aa39f42
c1424334e6157a2f7ec59c68e43000472f182b835d988f45ccbc88796aa39f42
Removing podman container lbocp42.service
Failed to stop lbocp42.service: Unit lbocp42.service not loaded.
Failed to execute operation: No such file or directory
Removing podman container ocp4lb.service
Failed to stop ocp4lb.service: Unit ocp4lb.service not loaded.
Failed to execute operation: No such file or directory
Removing podman container openshift-4-loadbalancer-ocp42.service
Removed symlink /etc/systemd/system/multi-user.target.wants/openshift-4-loadbalancer-ocp42.service.

OCP4 deployment removed
`

**Hardware Profile infomation**  
Please paste the result of the script found under lib//qubinode_hardware_profile.sh  

`Manufacturer: Supermicro
Product Name: X9DR3-F

System Memory
*************
Avaliable Memory: 528166304
Avaliable Human Memory: 503G

Storage Information
*******************
Avaliable Storage: 0
0
1863.68
970967
0
Avaliable Human Storage: Capacity Allocation
 
1.82 TiB
948.21 GiB
 

CPU INFO
***************
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Socket(s):             2
NUMA node(s):          2
Model name:            Intel(R) Xeon(R) CPU E5-2696 v2 @ 2.50GHz
NUMA node0 CPU(s):     0-11,24-35
NUMA node1 CPU(s):     12-23,36-47`

**Comment by tosin2013** [comment]
/home/qubi/qubinode-installer/inventory/inventory.3.11.rhel.gluster

**Comment by tosin2013** [comment]
Fixed in https://github.com/Qubinode/qubinode-installer/releases/tag/2.3.1
