### ISSUE TITLE
ERROR    authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'

### ISSUE THREAD

**Issue by tosin2013** [Qubinode/qubinode-installer#11]
virt-install --connect qemu:///system --import --name ocp-master01              --ram 16384 --vcpus 4              --disk /var/lib/libvirt/images/ocp-master01_vda.qcow2,format=qcow2,bus=virtio              --disk /var/lib/libvirt/data/ocp-master01/cidata.iso,device=cdrom              --network network=lunchbox              --autostart              --os-type=linux --os-variant=rhel7 --noautoconsole
ERROR    authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'

**Comment by tosin2013** [comment]
the fix is  sudo usermod --append --groups libvirt `whoami`

**Comment by flyemsafe** [comment]
This is fixed. It's on the roadmap to allow a regular user to manage libvirt.
