### ISSUE TITLE
The qubinode-installer should install nested rhv

### ISSUE THREAD

**Issue by flyemsafe** [Qubinode/qubinode-installer#111]
**Is your feature request related to a problem? Please describe.**
The installer should support deploying a single node or two node rhv cluster.

**Describe the solution you'd like**
Deploy RHV
```
./qubinode-installer -p rhv
```

**Comment by jeffcpullen** [comment]
@flyemsafe so the first issue I see with the RHV integration is how closely coupled all the scripts are tied to using the virsh command.

**Comment by flyemsafe** [comment]
> @flyemsafe so the first issue I see with the RHV integration is how closely coupled all the scripts are tied to using the virsh command.

So the idea for this feature is to deploy RHV nested. RHV will be just another set of VMs running atop KVM. If you have a system with 128G of ram, you could deploy a 2 node or 3 node RHV cluster. The Qubinode already function as a NFS server, so it can have NFS datastore. With 3 nodes, you can deploy RHHI.

Remember the approach is this: I have a single piece of hardware with enough resources and I want to run RH products to either simulate a production like a deployment or just to get familiar with the products.
