### ISSUE TITLE
[BUG] The installer fail to deploy kvm-vm

### ISSUE THREAD

**Issue by joecharles33** [Qubinode/qubinode-installer#117]
when running ./qubinode-installer for a fresh deployment, encountering the following error: ```TASK [deploy-kvm-vm : Push base image onto vm operating system disk] ********************************************************************************************************
Sunday 12 January 2020  09:05:58 -0500 (0:00:00.240)       0:00:15.080 ******** 
fatal: [localhost]: FAILED! => 
  msg: |-
    The conditional check '"Resize operation completed with no errors" in resize_os_disk_results.stdout' failed. The error was: error while evaluating conditional ("Resize operation completed with no errors" in resize_os_disk_results.stdout): Unable to look up a name or access an attribute in template string ({% if "Resize operation completed with no errors" in resize_os_disk_results.stdout %} True {% else %} False {% endif %}).
    Make sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable
```
![image](https://user-images.githubusercontent.com/47707671/72220319-85014c80-351d-11ea-9757-e1f0fe3df45e.png)

**Comment by flyemsafe** [comment]
DId you just ran ./qubinode-installer then choose option 1?

Where you using a release or the master or dev branch? I need to see more output from the play. Which version of ansible are you using?

**Comment by joecharles33** [comment]
option 1 was chosen, the dev branch was being used, ansible version 2.6 is currently installed. The above mentioned was all the playbook returned

**Comment by joecharles33** [comment]
this issue is not seen under release 2.2

**Comment by tosin2013** [comment]
Please test in https://github.com/Qubinode/qubinode-installer/releases/tag/2.3.1 @joecharles33

**Comment by tosin2013** [comment]
https://github.com/Qubinode/qubinode-installer/commit/1febe84455a25ef024ec115649b2e6f972aadb5e  This should be fixed in both branches
