### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by joecharles33** [Qubinode/qubinode-installer#125]
**Qubinode Version**  
Qubinode releasev2.2

```
for host in '$(echo $HOSTS)'
+ echo qbn-ocp3-master01.lab.example
+ ansible qbn-ocp3-master01.lab.example -i /tmp/tmp.qljASv42zW -m ping
+ tee -a /tmp/tmp.zhDYtikGcX
+ for host in '$(echo $HOSTS)'
+ echo qbn-ocp3-infra02.lab.example
+ ansible qbn-ocp3-infra02.lab.example -i /tmp/tmp.qljASv42zW -m ping
+ tee -a /tmp/tmp.zhDYtikGcX
```  

This following for loop get stuck during the installatioin, user intervention is often required, by hitting conctrol C to continue.

**Comment by tosin2013** [comment]
@joecharles33 Please test this issue in the https://github.com/Qubinode/qubinode-installer/releases/tag/2.3.1 release
