### ISSUE TITLE
[BUG]unable to add nfs-storage-provisioner

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#129]
**Qubinode Version**  
Qubinode releasev2.3 

**Describe the bug**
Installing ocp4, and it prompt our to configure the nfs-provisioner. Input as yes, it return unable to add:

```
NFS Server is configured and can be used for persistent storage.
 Do you want to configure nfs-provisioner? yes/no yes
No resources found in default namespace.
FATAL: File /usr/local/src/nfs-provisioner-rbac.yaml does not exist
No resources found in default namespace.
 Unable to add nfs storage provisioner, please investigate.
```

**To Reproduce**
1.  qubinode-installer -p ocp4

**Expected behavior**
Redhat host has been configured as NFS server and export the /export directory as the directory. Expect, the installation can make use the NFS server as storage

**Hardware Profile infomation**  
Please paste the result of the script found under lib//qubinode_hardware_profile.sh  
If script is not on your machine use the following link [lib/qubinode_hardware_profile.sh](https://github.com/Qubinode/qubinode-installer/blob/post_release/lib/qubinode_hardware_profile.sh)  

SYSTEM REPORT
Manufacturer: Supermicro
Product Name: X9DR3-F

System Memory
*************
Avaliable Memory: 528166180
Avaliable Human Memory: 503G

Storage Information
*******************
Avaliable Storage: 1863.68
Avaliable Human Storage: 1.82 TiB

CPU INFO
***************
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Socket(s):             2
NUMA node(s):          2
Model name:            Intel(R) Xeon(R) CPU E5-2696 v2 @ 2.50GHz
NUMA node0 CPU(s):     0-11,24-35
NUMA node1 CPU(s):     12-23,36-47

**Comment by flyemsafe** [comment]
This will be removed as a default installation option going forward.
