### ISSUE TITLE
[BUG]OCP4 cannot be started during installation

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#137]
**Qubinode Version**  
Qubinode releasev2.31

**Describe the bug**
Run qubinode-install -p ocp4. it continue to prompt out these errors:

DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource 

Finally, prompt out this error:
FATAL waiting for Kubernetes API: context deadline exceeded

**To Reproduce**
1. qubinode-install -p ocp4 -d
2. qubinode-install -p idm -d
3. qubinode-install -p ocp4

**Expected behavior**
Should be installed successful

**Screenshots**
`Start up computer nodes ----------------------------------------------------------------------------------------------------------------------------------------------- 1.27s
Start up Bootstrap node ----------------------------------------------------------------------------------------------------------------------------------------------- 0.76s
Playbook run took 0 days, 0 hours, 0 minutes, 25 seconds
DEBUG OpenShift Installer v4.3.1                   
DEBUG Built from commit 2055609f95b19322ee6cfdd0bea73399297c4a3e 
INFO Waiting up to 30m0s for the Kubernetes API at https://api.ocp42.lab.home:6443... 
DEBUG Still waiting for the Kubernetes API: Get https://api.ocp42.lab.home:6443/version?timeout=32s: net/http: TLS handshake timeout 
DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource 
DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource 
DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource 
DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource 
DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource 
DEBUG Still waiting for the Kubernetes API: Get https://api.ocp42.lab.home:6443/version?timeout=32s: net/http: TLS handshake timeout 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: Get https://api.ocp42.lab.home:6443/version?timeout=32s: net/http: request canceled (Client.Timeout exceeded while awaiting headers) 
DEBUG Still waiting for the Kubernetes API: Get https://api.ocp42.lab.home:6443/version?timeout=32s: context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
DEBUG Still waiting for the Kubernetes API: Get https://api.ocp42.lab.home:6443/version?timeout=32s: http2: server sent GOAWAY and closed the connection; LastStreamID=489, ErrCode=NO_ERROR, debug="" 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
DEBUG Still waiting for the Kubernetes API: the server has asked for the client to provide credentials 
ERROR Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Unauthorized 
INFO Use the following commands to gather logs from the cluster 
INFO openshift-install gather bootstrap --help    
FATAL waiting for Kubernetes API: context deadline exceeded 

 Registry storage for bate metal is required to complete the ocp4 cluster install.
 Additional informaiton is available here:
 https://red.ht/2QVJpPK

 The installer will attempt to configure storage.

 NFS Server is configured and can be used for persistent storage.
 Do you want to configure nfs-provisioner? yes/no  
`

**Additional context**

**Hardware Profile infomation**  
Please paste the result of the script found under lib//qubinode_hardware_profile.sh  
If script is not on your machine use the following link [lib/qubinode_hardware_profile.sh](https://github.com/Qubinode/qubinode-installer/blob/post_release/lib/qubinode_hardware_profile.sh)  
`SYSTEM REPORT
Manufacturer: Supermicro
Product Name: X9DR3-F

System Memory
*************
Avaliable Memory: 528166180
Avaliable Human Memory: 503G

Storage Information
*******************
Avaliable Storage: 1863.68
Avaliable Human Storage: 1.82 TiB

CPU INFO
***************
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Socket(s):             2
NUMA node(s):          2
Model name:            Intel(R) Xeon(R) CPU E5-2696 v2 @ 2.50GHz
NUMA node0 CPU(s):     0-11,24-35
NUMA node1 CPU(s):     12-23,36-47
`

**Comment by tosin2013** [comment]
For now we should hit no for the nfs storage. And then follow the manual steps. Where you able to login to your bootstrap node during the deployment process and look at the logs?

**Comment by tosin2013** [comment]
I see you should install idm before running the openshift install when you delete.  You do not have to uninstall idm. Just ocp4 for the Re-install.

**Comment by dingyeah33** [comment]
I try to resolve it by 2 options:
1. uninstall ocp4 and install it, it still has this error
2. uninstall ocp4, idm and reinstall idm and ocp4, still got this error.

Meanwhile, how I can access the bootstrap node to check the deployment log?

**Comment by tosin2013** [comment]
It should be 

## for bootstrap
 ssh -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no"  core@192.168.50.2

## for master 1
ssh -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no"  core@192.168.50.10

**Comment by dingyeah33** [comment]
I just remove all the components, including kvm, and re-install again.
This time, OCP4 can be deployed successfully.

`INFO Waiting up to 30m0s for the Kubernetes API at https://api.ocp42.lab.home:6443... 

DEBUG Still waiting for the Kubernetes API: Get https://api.ocp42.lab.home:6443/version?timeout=32s: net/http: TLS handshake timeout 

DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource 

DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource 

DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource 

DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource 

DEBUG Still waiting for the Kubernetes API: the server could not find the requested resource 

DEBUG Still waiting for the Kubernetes API: Get https://api.ocp42.lab.home:6443/version?timeout=32s: unexpected EOF 

DEBUG Still waiting for the Kubernetes API: Get https://api.ocp42.lab.home:6443/version?timeout=32s: net/http: TLS handshake timeout 

INFO API v1.16.2 up                               

INFO Waiting up to 30m0s for bootstrapping to complete... 

DEBUG Bootstrap status: complete                   

INFO It is now safe to remove the bootstrap resources 
`

Not sure, whether it is timeout issue or not.

**Comment by flyemsafe** [comment]
The installer is updating /etc/resolv.conf changing the DNS from IdM to 8.8.8.8.
