### ISSUE TITLE
[BUG] The installer should be more robust in identifying the rhel 7.7 qcow2 image

### ISSUE THREAD

**Issue by kjw3** [Qubinode/qubinode-installer#139]
**Qubinode Version**  
Qubinode releasev2.3.1

**Describe the bug**
The installer looks for a specific name of the RHEL 7.7 qcow2 file. This may not always be the same. Maybe there is a better way to examine the qcow2 files available in the qubinode-installer directory and determine if there is one suitable to use.

Currently the installer looks for:
rhel-server-7.7-update-2-x86_64-kvm.qcow2

```
Could not find /home/qubinode/qubinode-installer/rhel-server-7.7-update-2-x86_64-kvm.qcow2, please download the rhel-server-7.7-update-2-x86_64-kvm.qcow2 to /home/qubinode/qubinode-installer.

Please refer the documentation for additional information.
```

**To Reproduce**
1. Follow the instructions to get the qubinode installer
2. Download the latest RHEL 7.7 KVM guest image (which may not have the exact name of the installer expectation)
3. Run installer, can't locate the qcow2 file

**Expected behavior**
I think there could be some simple string evaluation to identify if rhel and 7.7 occur in the name of a qcow2 that is sitting in the qubinode-installer directory and make an assumption the qcow2 is safe to use.

**Comment by tosin2013** [comment]
Thanks for the feedback. Where you able to get around the issue?

**Comment by kjw3** [comment]
Sure. I just renamed the file to the name that the installer is expecting :).

More a suggestion than a blocking issue.

**Comment by tosin2013** [comment]
Here are the packages we use for qubinode 
https://github.com/Qubinode/qubinode-usb-imager/blob/master/templates/x11sdv-8c-tp8f.ks.j2
