### ISSUE TITLE
[BUG] RHSM step selects the wrong pool to attach

### ISSUE THREAD

**Issue by kjw3** [Qubinode/qubinode-installer#142]
**Qubinode Version**  
Qubinode release v2.3.1  

**Describe the bug**
During the rhsm step, the wrong pool was chosen from my RHN account. It chose my CloudForms Employee Subscription rather than Employee SKU.

**To Reproduce**
1. ./qubinode-installer -m rhsm
2. sudo subscription-manager list --consumed|grep 'Subscription Name'

**Expected behavior**
Expect the rhsm step to select an appropriate pool that has all the necessary repos available for the qubinode installer.

**Additional context**
qubinode@lunchbox:~ $ sudo subscription-manager unregister
Unregistering from: subscription.rhsm.redhat.com:443/subscription
System has been unregistered.
qubinode@lunchbox:~ $ sudo subscription-manager clean
All local data removed
qubinode@lunchbox:~ $ cd qubinode-installer/
qubinode@lunchbox:~/qubinode-installer $ ./qubinode-installer -m rhsm

 Registering system to rhsm using your username/password.
 Successfully registered .... to RHSM
Registering to: subscription.rhsm.redhat.com:443/subscription
The system has been registered with ID: .....
The registered system name is: ......

    *********************************
    *   RHSM registration complete  *
    *********************************

qubinode@lunchbox:~/qubinode-installer $ sudo subscription-manager list --consumed|grep 'Subscription Name'
Subscription Name:   CloudForms Employee Subscription
qubinode@lunchbox:~/qubinode-installer $ sudo subscription-manager list --available | grep 'Subscription Name:'
Subscription Name:   Employee SKU
Subscription Name:   Red Hat Satellite Employee Subscription
Subscription Name:   Red Hat Satellite Infrastructure Subscription
Subscription Name:   Red Hat OpenShift Container Platform Broker/Master Infrastructure for Power, LE (2 Cores)
Subscription Name:   Red Hat OpenShift Container Platform Broker/Master Infrastructure
Subscription Name:   CloudForms Employee Subscription
Subscription Name:   Red Hat OpenShift Container Platform Broker/Master Infrastructure for Power, LE (2 Cores, L3 Only)
Subscription Name:   Red Hat OpenShift Container Platform Broker/Master Infrastructure for Power, LE (2 Cores)
Subscription Name:   Employee SKU
Subscription Name:   Red Hat Virtualization Manager
Subscription Name:   Red Hat Virtualization Manager
Subscription Name:   Red Hat OpenShift Container Platform Broker/Master Infrastructure for Power, LE (2 Cores, L3 Only

**Comment by flyemsafe** [comment]
Looks like the below needs to be added to the lib/qubinode_ocp4.sh launcher.

```get_subscription_pool_id 'Red Hat OpenShift Container Platform'```
