### ISSUE TITLE
Add one more compute node during installation

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#143]
**Is your feature request related to a problem? Please describe.**

Try to add one more compute node during the installation.  I have changed the ocp4.yml compute_count to 3
https://github.com/Qubinode/qubinode-installer/blob/master/samples/ocp4.yml
Seem, it cannot create one more KVM VM instance for this new compute node. However, the installer try to start this VM at the end,  but, it cannot find it.

**Describe the solution you'd like**
Would like to add/reduce the nodes during the installation process by changing the configuration file

**Comment by dingyeah33** [comment]
Having changed couple files to have 3 compute nodes creation during installation as below:
1. lib/qubinode_cleanup_coreos_vms.sh
2. lib/qubinode_ocp4_utils.sh
3. lib/qubinode_deploy_ocp4_nodes.sh
4. samples/ocp4.yml
5. playbooks/vars/all.yml

Now, it can create the third compute nodes, but, it seem it has a startup problem. Screen cap has been attached:
![image](https://user-images.githubusercontent.com/6370369/77342303-f144cb80-6d6a-11ea-8c71-8df8bd77e467.png)

**Comment by flyemsafe** [comment]
@dingyeah33 The dev branch now includes code that deploys three nodes by default. We moved the OCP4 deployment to a single role [1].

If you wanted more nodes, you can add the following to samples/ocp4.yml before running the installer or playbooks/vars/ocp4.yml after installation.

```
# ocp4 nodes attributes
master_count: 3
compute_count: 3
```
There is also a dictionary to called *ocp4_instances* you can edit that to change the attributes of the VM, such attributes as memory, storage etc.. Consult the defaults/main.yml [2].

With this change, all the files that you have edited are no longer needed and will be removed when we release this code. The playbook that kicks off the install is playbooks/deploy_ocp4.yml. The launcher script is still lib/qubinode_ocp4.sh and we still use lib/qubinode_ocp4_utils.sh to provide auxiliary functions needed.

[1] https://github.com/Qubinode/ocp4-kvm-deployer
[2] https://github.com/Qubinode/ocp4-kvm-deployer/blob/master/defaults/main.yml

**Comment by dingyeah33** [comment]
@flyemsafe Just use dev branch to deploy ocp4, but, I got this error, any clue?

`TASK [add bootstrap to dns forward zone] **************************************************************************************************************************
Tuesday 24 March 2020  18:24:20 +0800 (0:00:00.100)       0:00:05.194 *********
fatal: [localhost]: FAILED! =>
  msg: |-
    The field 'vars' has an invalid value, which includes an undefined variable. The error was: 'vn_subnet' is undefined

    The error appears to have been in '/home/louie/qubinode-installer/playbooks/ocp4_02_configure_dns_entries.yml': line 26, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


        - name: add bootstrap to dns forward zone
          ^ here`

**Comment by tosin2013** [comment]
This feature has been added to the dev branch as a custome menu 
https://github.com/Qubinode/qubinode-installer/commit/1a997a1ae28d5bc5f61f5d2eeb454c643f6895a6Would you like a customize this deployment? yes/no yes

  Please choose an OpenShift Cluster Profile

  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Qubinode OpenShift 4.x Profiles
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1. Minimal Deployment
    2. Standard Deployment
    3. Standard Deployment with local-storage
    4. Custom Deployment
    5. Exit
 Enter choice [ 1 - 5] 4
    =========================
    Deployment Type: Custom
    =========================

    =========================
    This Deployment option is not supported. Limited assitance will be provided.
    =========================

    ========
    The Following can be changed
    Please submit a pull request for additional changes.
    ========
     - compute count 
     - local storage 


 Enter the number of compute nodes your would like? 3
 You entered 3, is this correct? yes/no yes

 Your compute_count is now set to 3
    =========================
    Select volume Mode: 
    =========================

    1) Filesystem - Presented to the OS as a file system export to be mounted.
    2) Block - Presented to the operating system (OS) as a block device.
 Enter choice [ 1 - 2] 1
 Continue with  Volume Mode for filesystem OpenShift deployment? yes/no yes
 Continue with custom OpenShift cluster deployment? yes/no 
```

```
