### ISSUE TITLE
[BUG]during install qubinode-installer fails to check and move rhel-server-7.7-update-2-x86_64-kvm.qcow2 file

### ISSUE THREAD

**Issue by amalivert** [Qubinode/qubinode-installer#153]
TASK [deploy-kvm-vm : fail if /var/lib/libvirt/images/rhel-server-7.7-update-2-x86_64-kvm.qcow2 does not exist] *****************************
Wednesday 25 March 2020  15:46:48 -0400 (0:00:00.341)       0:00:05.960 ******* 
fatal: [localhost -> localhost]: FAILED! => changed=false 
  msg: |-
    The qcow os template /var/lib/libvirt/images/rhel-server-7.7-update-2-x86_64-kvm.qcow2 does not exist.
    Please verify the variable os_qcow_template is set to the correct path
    or copy rhel-server-7.7-update-2-x86_64-kvm.qcow2 to /var/lib/libvirt/images/rhel-server-7.7-update-2-x86_64-kvm.qcow2.

**Comment by tosin2013** [comment]
https://github.com/Qubinode/qubinode-installer/pull/160
