### ISSUE TITLE
[Bug]Menu fix

### ISSUE THREAD

**Issue by joecharles33** [Qubinode/qubinode-installer#154]
1.
 ``` 
What is the username for the existing IdM server admin user? admin
  You entered , is this correct? yes/no 
```

2.
```
 What is the username for the existing IdM server admin user? admin
 You entered , is this correct? yes/no yes


 The Qubinode runs a Red Hat Identity Manager (IdM).
 Your username joe will be use as the admin user.
 Enter a password to be set for the IdM admin user and press [ENTER]: **********

```

**Describe the bug**
1- when the user enter his username, the installer fails to display the username entered by the user to standard output. see the above snippet.

2 - The installer prompts a user to enter a username, the installer fails to store the username entered by the user and instead use the user default user as the IDM admin user. 

**Expected behavior**
The installer should display the username entered by the user to standard output.

**Comment by tosin2013** [comment]
https://github.com/Qubinode/qubinode-installer/pull/160
