### ISSUE TITLE
[BUG]''kvm_host_ip'' is undefined'

### ISSUE THREAD

**Issue by amalivert** [Qubinode/qubinode-installer#156]
TASK [Copying over nfs-provisioner deployment] **********************************************************************************************
Wednesday 25 March 2020  21:58:51 -0400 (0:00:00.457)       0:08:45.234 ******* 
fatal: [localhost]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: ''kvm_host_ip'' is undefined'

The kvm_host_ip is defined in the playbooks/vars/kvm_hosts.yml

**Comment by flyemsafe** [comment]
The post installation of the nfs provisioner will be move to a option step that can be performed by the user in the next release.
