### ISSUE TITLE
[BUG]OCP4 installation using DEV branch

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#164]
**Qubinode Version**  
Qubinode releasev2.31 - DEV branch

**Describe the bug**
OCP 4 installation using advance installation mode, and it is stopped at ./qubinode-installer -m host

**To Reproduce**
1. ./qubinode-installer -m rhsm
/home/louie/qubinode-installer/lib/qubinode_kvmhost.sh: line 378: syntax error near unexpected token `}'
/home/louie/qubinode-installer/lib/qubinode_kvmhost.sh: line 378: `}'

2. ./qubinode-installer -m ansible
/home/louie/qubinode-installer/lib/qubinode_kvmhost.sh: line 378: syntax error near unexpected token `}'
/home/louie/qubinode-installer/lib/qubinode_kvmhost.sh: line 378: `}'

3. ./qubinode-installer -m host
/home/louie/qubinode-installer/lib/qubinode_kvmhost.sh: line 378: syntax error near unexpected token `}'
/home/louie/qubinode-installer/lib/qubinode_kvmhost.sh: line 378: `}'

/home/louie/qubinode-installer/lib/qubinode_menu_options.sh: line 89: qubinode_setup_kvm_host: command not found

**Comment by tosin2013** [comment]
The advanced installer is not ready in dev branch. Option 1 should work much better.

**Comment by dingyeah33** [comment]
Try to use option 1, but, it prompt out error on installing idm:

ansible-idm : Run the installer --------------------------------------------------------------- 339.12s
update system --------------------------------------------------------------------------------- 271.31s
ansible-idm : install IPA packages ------------------------------------------------------------ 165.50s
swygue-redhat-subscription : Enable repositories ---------------------------------------------- 105.02s
swygue-redhat-subscription : Register qbn-dns01 system using rhsm_user and rhsm_password ------- 87.61s
ansible-idm : Make sure firewalld is installed ------------------------------------------------- 80.66s
swygue-redhat-subscription : save enabled redhat repositories ---------------------------------- 31.00s
swygue-redhat-subscription : save enabled redhat repositories ---------------------------------- 24.32s
swygue-redhat-subscription : refresh subscriptions --------------------------------------------- 14.25s
swygue-redhat-subscription : refresh subscriptions --------------------------------------------- 13.96s
swygue-redhat-subscription : refresh subscriptions --------------------------------------------- 13.71s
swygue-redhat-subscription : removing system rhsm registration --------------------------------- 11.46s
ansible-idm : waiting for IDM services to come up ---------------------------------------------- 10.70s
swygue-redhat-subscription : check if system is already registered ------------------------------ 7.80s
swygue-redhat-subscription : check system registration status ----------------------------------- 5.88s
ansible-idm : Enable IDAM ldap, ldaps and replication ports ------------------------------------- 2.66s
ansible-idm : reload firewalld ------------------------------------------------------------------ 1.43s
ansible-idm : Enable and start firewalld -------------------------------------------------------- 1.28s
ansible-idm : set hostname ---------------------------------------------------------------------- 1.10s
ansible-idm : create template script for ipa-install -------------------------------------------- 1.09s
Playbook run took 0 days, 0 hours, 20 minutes, 5 seconds
 IDM Server was not properly deployed please verify deployment.

**Comment by tosin2013** [comment]
In order to debug qubinode do the following 
**open the qubinode script**
```
$ vim qubinode-installer 
```

**Uncomment lines 29 and 30**
29 willl give you a lot of infomation
```
 28 # Uncomment for debugging
 29 #export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 30 #set -x
```

**Save the file and rerun the script**
