### ISSUE TITLE
Create a password length check for ipa server 

### ISSUE THREAD

**Issue by tosin2013** [Qubinode/qubinode-installer#20]
Thursday 15 August 2019  17:56:21 -0400 (0:00:00.812)       0:14:38.095 ******* 
fatal: [ocp-dns01]: FAILED! => {
    "changed": true, 
    "cmd": "/root/ipa-srv-install.sh", 
    "delta": "0:00:00.608630", 
    "end": "2019-08-15 17:56:21.930621", 
    "rc": 2, 
    "start": "2019-08-15 17:56:21.321991"
}

STDERR:

ipapython.install.cli: DEBUG    Logging to /var/log/ipaserver-install.log
Usage: ipa-server-install [options]

ipa-server-install: error: option admin-password: Password must be at least 8 characters long
ipapython.admintool: DEBUG      File "/usr/lib/python2.7/site-packages/ipapython/admintool.py", line 178, in execute
    return_value = self.run()
  File "/usr/lib/python2.7/site-packages/ipapython/install/cli.py", line 310, in run
    self.option_parser.error("{0}: {1}".format(desc, e))
  File "/usr/lib64/python2.7/optparse.py", line 1583, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/usr/lib64/python2.7/optparse.py", line 1573, in exit
    sys.exit(status)

ipapython.admintool: DEBUG    The ipa-server-install command failed, exception: SystemExit: 2
ipapython.admintool: ERROR    The ipa-server-install command failed.

**Comment by flyemsafe** [comment]
fixed 0f8c0c938469cce0bf748d78a57a9096173edca2
