### ISSUE TITLE
This system has no repositories available through subscriptions vm's

### ISSUE THREAD

**Issue by tosin2013** [Qubinode/qubinode-installer#22]
TASK [Enable rhel-7-server-rpms repository] *******************************************************************************************************************
Friday 16 August 2019  09:59:51 -0400 (0:00:07.378)       0:00:10.648 ********* 
fatal: [ocp-node01.lab.example]: FAILED! => {
    "changed": false
}

MSG:

This system has no repositories available through subscriptions

fatal: [ocp-infra02.lab.example]: FAILED! => {
    "changed": false
}

MSG:

This system has no repositories available through subscriptions

fatal: [ocp-infra01.lab.example]: FAILED! => {
    "changed": false
}

MSG:

This system has no repositories available through subscriptions

fatal: [ocp-node02.lab.example]: FAILED! => {
    "changed": false
}

MSG:

This system has no repositories available through subscriptions

**Comment by tosin2013** [comment]
https://access.redhat.com/solutions/1981673

**Comment by flyemsafe** [comment]
fixed: 5b3614896f5d7a8bf01811c4e517716ffbd7b3de
