### ISSUE TITLE
[BUG]Cannot startup the OCP4 cluster after properly shutdown

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#228]
**Qubinode Version**  
Qubinode releasev2.4 

**Describe the bug**
Having waited for 24 hours, and use the command "qubinode-installer -p ocp4 -m shutdown" to shutdown the cluster. It has been completed the shutdown without any issue.
Then try to startup the cluster with the command "qubinode-installer -p ocp4 -m startup", and it fail to bring up the OCP4 cluster.

`TASK [ocp4-kvm-deployer : fail a total 3 is not found] *************************************************
Monday 22 June 2020  21:18:24 +0800 (0:04:17.686)       0:04:23.837 *********** 
fatal: [localhost]: FAILED! => changed=false 
  msg: Was not able to confirm all 3 master nodes are up`

Using the command "oc get nodes" it prompt out the below error:
error: You must be logged in to the server (Unauthorized)

Try to login with "oc login -u <user>", it has this message:
error: EOF

**To Reproduce**
1. qubinode-installer -p ocp4 -m shutdown
2. Restart the RHEL host
3. wait for the qbn-dns01 startup
4. qubinode-installer -p ocp4 -m startup
5. All 3 master nodes are up and running

**Expected behavior**
Expected the OCP4 is startup and can be login

**Screenshots**
`PLAY [Deploy OpenShift 4.x Cluster] ********************************************************************

TASK [Gathering Facts] *********************************************************************************
Monday 22 June 2020  21:14:00 +0800 (0:00:00.096)       0:00:00.096 *********** 
ok: [localhost]

TASK [ocp4-kvm-deployer : get qbn-lb container info] ***************************************************
Monday 22 June 2020  21:14:02 +0800 (0:00:01.827)       0:00:01.924 *********** 
ok: [localhost]

TASK [ocp4-kvm-deployer : set qbn-lb container state] **************************************************
Monday 22 June 2020  21:14:03 +0800 (0:00:00.550)       0:00:02.475 *********** 
ok: [localhost]

TASK [ocp4-kvm-deployer : check if Loadbalancer SystemD service exists] ********************************
Monday 22 June 2020  21:14:03 +0800 (0:00:00.072)       0:00:02.547 *********** 
ok: [localhost]

TASK [ocp4-kvm-deployer : start the loadbancer systemd service qbn-lb.service] *************************
Monday 22 June 2020  21:14:03 +0800 (0:00:00.437)       0:00:02.984 *********** 
skipping: [localhost]

TASK [ocp4-kvm-deployer : collect all services state] **************************************************
Monday 22 June 2020  21:14:03 +0800 (0:00:00.057)       0:00:03.041 *********** 
ok: [localhost]

TASK [ocp4-kvm-deployer : fail if the systemd service qbn-lb.service is not running] *******************
Monday 22 June 2020  21:14:04 +0800 (0:00:00.933)       0:00:03.975 *********** 
skipping: [localhost]

TASK [ocp4-kvm-deployer : list all libvirt vms] ********************************************************
Monday 22 June 2020  21:14:04 +0800 (0:00:00.096)       0:00:04.071 *********** 
ok: [localhost]

TASK [ocp4-kvm-deployer : start ocp master nodes] ******************************************************
Monday 22 June 2020  21:14:05 +0800 (0:00:00.448)       0:00:04.520 *********** 
changed: [localhost] => (item=0)
changed: [localhost] => (item=1)
changed: [localhost] => (item=2)

TASK [ocp4-kvm-deployer : wait for master nodes to be available] ***************************************
Monday 22 June 2020  21:14:06 +0800 (0:00:01.630)       0:00:06.151 *********** 
FAILED - RETRYING: wait for master nodes to be available (18 retries left).
FAILED - RETRYING: wait for master nodes to be available (17 retries left).
FAILED - RETRYING: wait for master nodes to be available (16 retries left).
FAILED - RETRYING: wait for master nodes to be available (15 retries left).
FAILED - RETRYING: wait for master nodes to be available (14 retries left).
FAILED - RETRYING: wait for master nodes to be available (13 retries left).
FAILED - RETRYING: wait for master nodes to be available (12 retries left).
FAILED - RETRYING: wait for master nodes to be available (11 retries left).
FAILED - RETRYING: wait for master nodes to be available (10 retries left).
FAILED - RETRYING: wait for master nodes to be available (9 retries left).
FAILED - RETRYING: wait for master nodes to be available (8 retries left).
FAILED - RETRYING: wait for master nodes to be available (7 retries left).
FAILED - RETRYING: wait for master nodes to be available (6 retries left).
FAILED - RETRYING: wait for master nodes to be available (5 retries left).
FAILED - RETRYING: wait for master nodes to be available (4 retries left).
FAILED - RETRYING: wait for master nodes to be available (3 retries left).
FAILED - RETRYING: wait for master nodes to be available (2 retries left).
FAILED - RETRYING: wait for master nodes to be available (1 retries left).
fatal: [localhost]: FAILED! => changed=false 
  attempts: 18
  cmd: |-
    /usr/local/bin/oc get nodes -o wide --no-headers=true | grep master| grep Ready|wc -l
  delta: '0:00:00.210701'
  end: '2020-06-22 21:18:24.524286'
  rc: 0
  start: '2020-06-22 21:18:24.313585'
  stderr: 'error: You must be logged in to the server (Unauthorized)'
  stderr_lines: <omitted>
  stdout: '0'
  stdout_lines: <omitted>
...ignoring

TASK [ocp4-kvm-deployer : fail a total 3 is not found] *************************************************
Monday 22 June 2020  21:18:24 +0800 (0:04:17.686)       0:04:23.837 *********** 
fatal: [localhost]: FAILED! => changed=false 
  msg: Was not able to confirm all 3 master nodes are up

PLAY RECAP *********************************************************************************************
localhost                  : ok=8    changed=1    unreachable=0    failed=1    skipped=2    rescued=0    ignored=1   

Monday 22 June 2020  21:18:24 +0800 (0:00:00.052)       0:04:23.889 *********** 
=============================================================================== 
ocp4-kvm-deployer : wait for master nodes to be available ------------------------------------- 257.69s
Gathering Facts --------------------------------------------------------------------------------- 1.83s
ocp4-kvm-deployer : start ocp master nodes ------------------------------------------------------ 1.63s
ocp4-kvm-deployer : collect all services state -------------------------------------------------- 0.93s
ocp4-kvm-deployer : get qbn-lb container info --------------------------------------------------- 0.55s
ocp4-kvm-deployer : list all libvirt vms -------------------------------------------------------- 0.45s
ocp4-kvm-deployer : check if Loadbalancer SystemD service exists -------------------------------- 0.44s
ocp4-kvm-deployer : fail if the systemd service qbn-lb.service is not running ------------------- 0.10s
ocp4-kvm-deployer : set qbn-lb container state -------------------------------------------------- 0.07s
ocp4-kvm-deployer : start the loadbancer systemd service qbn-lb.service ------------------------- 0.06s
ocp4-kvm-deployer : fail a total 3 is not found ------------------------------------------------- 0.05s
Playbook run took 0 days, 0 hours, 4 minutes, 23 seconds
`

**Hardware Profile infomation**  
`**Hardware Profile infomation**

SYSTEM REPORT

Manufacturer: Supermicro

Product Name: X9DR3-F

System Memory

Avaliable Memory: 528166172

Avaliable Human Memory: 503G

Storage Information

Avaliable Storage: 0

0

1863.68

970967

0

Avaliable Human Storage: Capacity Allocation

1.82 TiB

948.21 GiB

CPU INFO

CPU(s):                48

On-line CPU(s) list:   0-47

Thread(s) per core:    2

Socket(s):             2

NUMA node(s):          2

Model name:            Intel(R) Xeon(R) CPU E5-2696 v2 @ 2.50GHz

NUMA node0 CPU(s):     0-11,24-35

NUMA node1 CPU(s):     12-23,36-47`

**Comment by flyemsafe** [comment]
I think the startup ocp needs to be updated. You no longer have to wait 24hrs before you can shutdown the cluster. Can you check to see if there are any pending csr's.

```
oc get csr

# You can approve them like this
/usr/local/bin/oc get csr -ojson | jq -r '.items[] | select(.status == {} ) | .metadata.name' | xargs /usr/local/bin/oc adm certificate approve
```

We need to implement something like [this](https://github.com/redhat-cop/agnosticd/blob/development/ansible/configs/ocp4-cluster/lifecycle_hook_post_start.yml#L34) for the startup.

**Comment by dingyeah33** [comment]
Try to re-install with v2.41 and will test it later
