### ISSUE TITLE
[BUG]v2.4.1 Installation error on running "qubiunode-installer -m host"

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#230]
**Qubinode Version**  
Qubinode releasev2.4.1

**Describe the bug**
qubinode-installer -m host with the below error:

`TASK [qubinode_kvmhost_setup : fail] *********************************************************
Tuesday 23 June 2020  23:44:05 +0800 (0:00:00.057)       0:00:06.573 ********** 
fatal: [localhost]: FAILED! => changed=false 
  msg: Bailing out. this play requires 'kvm_host_interface' KVM host interface
`

**To Reproduce**
1. qubinode-installer -m setup
2. qubinode-installer -m rhsm
3. qubinode-installer -m ansible
4. qubinode-installer -m host

**Expected behavior**
No error for this command

**Screenshots**
`<pre>  RHEL release is set to the supported release: Release: 7.8 Downloading required roles

<font color="#FCE94F"><b>    *******************************</b></font>
<font color="#FCE94F"><b>    *   Ansible Setup Complete   *</b></font>
<font color="#FCE94F"><b>    *******************************</b></font>

 <font color="#729FCF"><b>Setting up qubinode system</b></font>

PLAY [setup KVM host] ************************************************************************

TASK [Gathering Facts] ***********************************************************************
Tuesday 23 June 2020  23:43:58 +0800 (0:00:00.067)       0:00:00.067 ********** 
<font color="#4E9A06">ok: [localhost]</font>

TASK [ensure backup folder is created] *******************************************************
Tuesday 23 June 2020  23:44:00 +0800 (0:00:01.576)       0:00:01.644 ********** 
<font color="#4E9A06">ok: [localhost]</font>

TASK [fail] **********************************************************************************
Tuesday 23 June 2020  23:44:00 +0800 (0:00:00.524)       0:00:02.168 ********** 
<font color="#06989A">skipping: [localhost]</font>

TASK [fail] **********************************************************************************
Tuesday 23 June 2020  23:44:00 +0800 (0:00:00.074)       0:00:02.243 ********** 
<font color="#06989A">skipping: [localhost]</font>

TASK [create libvirt logical volume] *********************************************************
Tuesday 23 June 2020  23:44:00 +0800 (0:00:00.071)       0:00:02.315 ********** 

TASK [swygue-lvm : check system file system] *************************************************
Tuesday 23 June 2020  23:44:00 +0800 (0:00:00.125)       0:00:02.440 ********** 
<font color="#06989A">included: /home/louie/qubinode-installer/playbooks/roles/swygue-lvm/tasks/precheck.yml for localhost</font>

TASK [swygue-lvm : ensure lvm2 is installed] *************************************************
Tuesday 23 June 2020  23:44:01 +0800 (0:00:00.101)       0:00:02.542 ********** 
<font color="#4E9A06">ok: [localhost]</font>

TASK [swygue-lvm : checking if /dev/nvme0n1 exist] *******************************************
Tuesday 23 June 2020  23:44:01 +0800 (0:00:00.490)       0:00:03.032 ********** 
<font color="#4E9A06">ok: [localhost]</font>

TASK [swygue-lvm : fail] *********************************************************************
Tuesday 23 June 2020  23:44:01 +0800 (0:00:00.442)       0:00:03.475 ********** 
<font color="#06989A">skipping: [localhost]</font>

TASK [swygue-lvm : set_fact] *****************************************************************
Tuesday 23 June 2020  23:44:01 +0800 (0:00:00.050)       0:00:03.526 ********** 
<font color="#4E9A06">ok: [localhost]</font>

TASK [swygue-lvm : check if the vg_qubi is on the device /dev/nvme0n1] ***********************
Tuesday 23 June 2020  23:44:02 +0800 (0:00:00.058)       0:00:03.585 ********** 
<font color="#4E9A06">ok: [localhost]</font>

TASK [swygue-lvm : set_fact] *****************************************************************
Tuesday 23 June 2020  23:44:02 +0800 (0:00:00.300)       0:00:03.885 ********** 
<font color="#4E9A06">ok: [localhost]</font>

TASK [swygue-lvm : check if the vg_qubi exist] ***********************************************
Tuesday 23 June 2020  23:44:02 +0800 (0:00:00.053)       0:00:03.939 ********** 
<font color="#4E9A06">ok: [localhost]</font>

TASK [swygue-lvm : set_fact] *****************************************************************
Tuesday 23 June 2020  23:44:02 +0800 (0:00:00.267)       0:00:04.206 ********** 
<font color="#4E9A06">ok: [localhost]</font>

TASK [swygue-lvm : set_fact] *****************************************************************
Tuesday 23 June 2020  23:44:02 +0800 (0:00:00.054)       0:00:04.261 ********** 
<font color="#4E9A06">ok: [localhost]</font>

TASK [swygue-lvm : fail] *********************************************************************
Tuesday 23 June 2020  23:44:02 +0800 (0:00:00.053)       0:00:04.314 ********** 
<font color="#06989A">skipping: [localhost]</font>

TASK [swygue-lvm : set_fact] *****************************************************************
Tuesday 23 June 2020  23:44:02 +0800 (0:00:00.049)       0:00:04.364 ********** 
<font color="#4E9A06">ok: [localhost]</font>

TASK [swygue-lvm : debug] ********************************************************************
Tuesday 23 June 2020  23:44:02 +0800 (0:00:00.052)       0:00:04.417 ********** 
<font color="#06989A">skipping: [localhost]</font>

TASK [swygue-lvm : deploy lvm filesystem] ****************************************************
Tuesday 23 June 2020  23:44:02 +0800 (0:00:00.051)       0:00:04.469 ********** 
<font color="#06989A">included: /home/louie/qubinode-installer/playbooks/roles/swygue-lvm/tasks/deploy.yml for localhost</font>

TASK [swygue-lvm : Create Volume Group] ******************************************************
Tuesday 23 June 2020  23:44:03 +0800 (0:00:00.109)       0:00:04.578 ********** 
<font color="#06989A">skipping: [localhost]</font>

TASK [swygue-lvm : create custom logical volumes] ********************************************
Tuesday 23 June 2020  23:44:03 +0800 (0:00:00.055)       0:00:04.633 ********** 
<font color="#06989A">skipping: [localhost] =&gt; (item={u&apos;size&apos;: u&apos;+100%FREE&apos;, u&apos;name&apos;: u&apos;qubi_images&apos;, u&apos;mount_dir&apos;: u&apos;/var/lib/libvirt/images&apos;, u&apos;fstype&apos;: u&apos;xfs&apos;}) </font>

TASK [swygue-lvm : Ensure filesystems are created] *******************************************
Tuesday 23 June 2020  23:44:03 +0800 (0:00:00.059)       0:00:04.693 ********** 
<font color="#06989A">skipping: [localhost] =&gt; (item={u&apos;size&apos;: u&apos;+100%FREE&apos;, u&apos;name&apos;: u&apos;qubi_images&apos;, u&apos;mount_dir&apos;: u&apos;/var/lib/libvirt/images&apos;, u&apos;fstype&apos;: u&apos;xfs&apos;}) </font>

TASK [swygue-lvm : Ensure mount points are created] ******************************************
Tuesday 23 June 2020  23:44:03 +0800 (0:00:00.060)       0:00:04.754 ********** 
<font color="#06989A">skipping: [localhost] =&gt; (item={u&apos;size&apos;: u&apos;+100%FREE&apos;, u&apos;name&apos;: u&apos;qubi_images&apos;, u&apos;mount_dir&apos;: u&apos;/var/lib/libvirt/images&apos;, u&apos;fstype&apos;: u&apos;xfs&apos;}) </font>

TASK [swygue-lvm : Config mount points in fstab] *********************************************
Tuesday 23 June 2020  23:44:03 +0800 (0:00:00.059)       0:00:04.813 ********** 
<font color="#4E9A06">ok: [localhost] =&gt; (item={u&apos;size&apos;: u&apos;+100%FREE&apos;, u&apos;name&apos;: u&apos;qubi_images&apos;, u&apos;mount_dir&apos;: u&apos;/var/lib/libvirt/images&apos;, u&apos;fstype&apos;: u&apos;xfs&apos;})</font>
<font color="#AD7FA8"><b>[WARNING]: The value 0 (type int) in a string field was converted to u&apos;0&apos; (type string). If</b></font>
<font color="#AD7FA8"><b>this does not look like what you expect, quote the entire value to ensure it does not change.</b></font>

TASK [swygue-lvm : show device info] *********************************************************
Tuesday 23 June 2020  23:44:03 +0800 (0:00:00.479)       0:00:05.293 ********** 
<font color="#06989A">skipping: [localhost] =&gt; (item={u&apos;size&apos;: u&apos;+100%FREE&apos;, u&apos;name&apos;: u&apos;qubi_images&apos;, u&apos;mount_dir&apos;: u&apos;/var/lib/libvirt/images&apos;, u&apos;fstype&apos;: u&apos;xfs&apos;}) </font>
<font color="#06989A">skipping: [localhost]</font>

TASK [fail] **********************************************************************************
Tuesday 23 June 2020  23:44:03 +0800 (0:00:00.062)       0:00:05.355 ********** 
<font color="#06989A">skipping: [localhost]</font>

TASK [Check whether ifcfg- contains &quot;UUID&quot;] **************************************************
Tuesday 23 June 2020  23:44:03 +0800 (0:00:00.052)       0:00:05.408 ********** 
<font color="#CC0000">fatal: [localhost]: FAILED! =&gt; changed=true </font>
<font color="#CC0000">  cmd:</font>
<font color="#CC0000">  - grep</font>
<font color="#CC0000">  - -Fxq</font>
<font color="#CC0000">  - UUID</font>
<font color="#CC0000">  - /etc/sysconfig/network-scripts/ifcfg-</font>
<font color="#CC0000">  delta: &apos;0:00:00.003393&apos;</font>
<font color="#CC0000">  end: &apos;2020-06-23 23:44:04.053347&apos;</font>
<font color="#CC0000">  msg: non-zero return code</font>
<font color="#CC0000">  rc: 2</font>
<font color="#CC0000">  start: &apos;2020-06-23 23:44:04.049954&apos;</font>
<font color="#CC0000">  stderr: &apos;grep: /etc/sysconfig/network-scripts/ifcfg-: No such file or directory&apos;</font>
<font color="#CC0000">  stderr_lines: &lt;omitted&gt;</font>
<font color="#CC0000">  stdout: &apos;&apos;</font>
<font color="#CC0000">  stdout_lines: &lt;omitted&gt;</font>
<font color="#06989A">...ignoring</font>

TASK [check if ifcfg- backup file exists] ****************************************************
Tuesday 23 June 2020  23:44:04 +0800 (0:00:00.273)       0:00:05.681 ********** 
<font color="#4E9A06">ok: [localhost -&gt; 127.0.0.1]</font>

TASK [backup  ifcfg-] ************************************************************************
Tuesday 23 June 2020  23:44:04 +0800 (0:00:00.484)       0:00:06.165 ********** 
<font color="#06989A">skipping: [localhost]</font>

TASK [running KVM host setup] ****************************************************************
Tuesday 23 June 2020  23:44:04 +0800 (0:00:00.052)       0:00:06.218 ********** 
<font color="#AD7FA8"><b>[WARNING]: While constructing a mapping from /home/louie/qubinode-</b></font>
<font color="#AD7FA8"><b>installer/playbooks/roles/qubinode_kvmhost_setup/defaults/main.yml, line 3, column 1, found a</b></font>
<font color="#AD7FA8"><b>duplicate dict key (libvirt_host_networks). Using last defined value only.</b></font>

TASK [qubinode_kvmhost_setup : Display all variables/facts known for a host] *****************
Tuesday 23 June 2020  23:44:04 +0800 (0:00:00.113)       0:00:06.331 ********** 
<font color="#4E9A06">ok: [localhost] =&gt; </font>
<font color="#4E9A06">  libvirt_host_networks:</font>
<font color="#4E9A06">  - compute_count: 2</font>
<font color="#4E9A06">    create: true</font>
<font color="#4E9A06">    external_domain: lab.home</font>
<font color="#4E9A06">    gateway: 192.168.50.1</font>
<font color="#4E9A06">    int_domain: compute.local</font>
<font color="#4E9A06">    mac_start: &apos;52:54:00:&apos;</font>
<font color="#4E9A06">    mask: 255.255.255.0</font>
<font color="#4E9A06">    master_count: 3</font>
<font color="#4E9A06">    mode: nat</font>
<font color="#4E9A06">    name: qbn</font>
<font color="#4E9A06">    subnet: 192.168.50.0</font>
<font color="#4E9A06">  - bridge_device: qubibr0</font>
<font color="#4E9A06">    bridge_slave_dev: &apos;&apos;</font>
<font color="#4E9A06">    create: false</font>
<font color="#4E9A06">    gateway: 192.168.1.160</font>
<font color="#4E9A06">    ifcfg_bootproto: none</font>
<font color="#4E9A06">    ifcfg_type: Bridge</font>
<font color="#4E9A06">    ipaddress: 192.168.1.140</font>
<font color="#4E9A06">    mac: 00:25:90:98:64:b0</font>
<font color="#4E9A06">    mask: 255.255.255.0</font>
<font color="#4E9A06">    mask_prefix: 24</font>
<font color="#4E9A06">    mode: bridge</font>
<font color="#4E9A06">    name: qubinet</font>

TASK [qubinode_kvmhost_setup : validate variables are defined] *******************************
Tuesday 23 June 2020  23:44:04 +0800 (0:00:00.069)       0:00:06.401 ********** 
<font color="#06989A">included: /home/louie/qubinode-installer/playbooks/roles/qubinode_kvmhost_setup/tasks/verify_variables.yml for localhost</font>

TASK [qubinode_kvmhost_setup : fail] *********************************************************
Tuesday 23 June 2020  23:44:04 +0800 (0:00:00.114)       0:00:06.515 ********** 
<font color="#06989A">skipping: [localhost]</font>

TASK [qubinode_kvmhost_setup : fail] *********************************************************
Tuesday 23 June 2020  23:44:05 +0800 (0:00:00.057)       0:00:06.573 ********** 
<font color="#CC0000">fatal: [localhost]: FAILED! =&gt; changed=false </font>
<font color="#CC0000">  msg: Bailing out. this play requires &apos;kvm_host_interface&apos; KVM host interface</font>

PLAY RECAP ***********************************************************************************
<font color="#CC0000">localhost</font>                  : <font color="#4E9A06">ok=18  </font> <font color="#C4A000">changed=1   </font> unreachable=0    <font color="#CC0000">failed=1   </font> <font color="#06989A">skipped=13  </font> rescued=0    <font color="#AD7FA8"><b>ignored=1   </b></font>

Tuesday 23 June 2020  23:44:05 +0800 (0:00:00.085)       0:00:06.659 ********** 
=============================================================================== 
Gathering Facts ----------------------------------------------------------------------- 1.58s
ensure backup folder is created ------------------------------------------------------- 0.52s
swygue-lvm : ensure lvm2 is installed ------------------------------------------------- 0.49s
check if ifcfg- backup file exists ---------------------------------------------------- 0.48s
swygue-lvm : Config mount points in fstab --------------------------------------------- 0.48s
swygue-lvm : checking if /dev/nvme0n1 exist ------------------------------------------- 0.44s
swygue-lvm : check if the vg_qubi is on the device /dev/nvme0n1 ----------------------- 0.30s
Check whether ifcfg- contains &quot;UUID&quot; -------------------------------------------------- 0.27s
swygue-lvm : check if the vg_qubi exist ----------------------------------------------- 0.27s
create libvirt logical volume --------------------------------------------------------- 0.13s
qubinode_kvmhost_setup : validate variables are defined ------------------------------- 0.11s
running KVM host setup ---------------------------------------------------------------- 0.11s
swygue-lvm : deploy lvm filesystem ---------------------------------------------------- 0.11s
swygue-lvm : check system file system ------------------------------------------------- 0.10s
qubinode_kvmhost_setup : fail --------------------------------------------------------- 0.09s
fail ---------------------------------------------------------------------------------- 0.07s
fail ---------------------------------------------------------------------------------- 0.07s
qubinode_kvmhost_setup : Display all variables/facts known for a host ----------------- 0.07s
swygue-lvm : show device info --------------------------------------------------------- 0.06s
swygue-lvm : Ensure filesystems are created ------------------------------------------- 0.06s
Playbook run took 0 days, 0 hours, 0 minutes, 6 seconds
</pre>`

**Hardware Profile infomation**  
`<pre>SYSTEM REPORT
Manufacturer: Supermicro
Product Name: X9DR3-F

System Memory
*************
Avaliable Memory: 528166172
Avaliable Human Memory: 503G

Storage Information
*******************
Avaliable Storage: 0
0
1863.68
970967
0
Avaliable Human Storage: Capacity Allocation
 
1.82 TiB
948.21 GiB
 

CPU INFO
***************
CPU(s):                48
On-line CPU(s) list:   0-47
Thread(s) per core:    2
Socket(s):             2
NUMA node(s):          2
Model name:            Intel(R) Xeon(R) CPU E5-2696 v2 @ 2.50GHz
NUMA node0 CPU(s):     0-11,24-35
NUMA node1 CPU(s):     12-23,36-47
</pre>`

**Comment by tosin2013** [comment]
@dingyeah33 Do you have a hard requirement on RHEL 7

**Comment by dingyeah33** [comment]
> @dingyeah33 Do you have a hard requirement on RHEL 7

No preference on RHEL 7. But, you mean I need to upgrade the KVM host to RHEL 8? How about the idm? Use RHEL 8 qcow image as well?

**Comment by tosin2013** [comment]
Just the kvm host can be RHEL 8 the qcow can be 7.8. @dingyeah33  would you like to be included when we perform our next release.

**Comment by dingyeah33** [comment]
Sure and thx for your info. I will try to upgrade my KVM host to RHEL 8 tonite. Any suggestion on the RHEL 8 release? Just upgrade to the latest one?

**Comment by tosin2013** [comment]
We are all using 8.2 right now.

**Comment by dingyeah33** [comment]
Just have a update. Seem I need to delete all the bridge networks before re-installation
