### ISSUE TITLE
[BUG]Could not find the libvirt network qubibr0 (dev branch)

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#244]
**Qubinode Version**  
Qubinode releasev2.4.1 Dev branch

**Describe the bug**
 ******************************
 * KVM Host Setup Fail   *
 *****************************

Could not find the libvirt network qubibr0 

But no failed entry of the playbook

**To Reproduce**
1. qubinode-installer -m host

**Expected behavior**
No error is prompt out

**Additional context**
Virtual network qubinet, which connected to qubibr0 network, is created

ip link output:
enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master qubibr0 state UP mode DEFAULT group default qlen 1000
 link/ether 00:25:90:98:64:b0 brd ff:ff:ff:ff:ff:ff
qubibr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
 link/ether 00:25:90:98:64:b0 brd ff:ff:ff:ff:ff:ff

**Comment by flyemsafe** [comment]
This should be fixed now, try the latest dev branch.

**Comment by tosin2013** [comment]
This should be fixed in the v2.4.2 release 
https://github.com/Qubinode/qubinode-installer/commit/9c78a4458c66b562b28adf9d6ec3c4b9c7946138
