### ISSUE TITLE
[BUG]Error on creating idm VM using dev branch

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#248]
**Qubinode Version**  
Qubinode releasevX.X  

**Describe the bug**
Creating idm VM, it has the below error:

TASK [deploy-kvm-vm : make sure resolv.conf is updated] *************************************************************
Friday 10 July 2020  16:49:15 +0800 (0:00:00.926)       0:01:11.916 *********** 
fatal: [localhost -> 192.168.1.139]: FAILED! => changed=false 
  module_stderr: |-
    Shared connection to 192.168.1.139 closed.
  module_stdout: |-
    /bin/sh: /usr/bin/python: No such file or directory
  msg: |-
    The module failed to execute correctly, you probably need to set the interpreter.
    See stdout/stderr for the exact error
  rc: 127

**To Reproduce**
1. qubinode-installer -p idm

**Expected behavior**
idm VM should be created without error

**Additional context**
idm VM seem that is created and I can ping the IP address without error
idm VM is created by RHEL 8.2 qcow image

**Comment by dingyeah33** [comment]
Just add this statements at ansible.cfg, delete idm VM and deploy again. No error come out.
interpreter_python  = auto

**Comment by tosin2013** [comment]
This should be fixed in the v2.4.2 release 
https://github.com/Qubinode/qubinode-installer/commit/9c78a4458c66b562b28adf9d6ec3c4b9c7946138
