### ISSUE TITLE
[BUG]Could not locate copy_qcow_image.yml

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#253]
**Qubinode Version**  
Qubinode releasev2.4.2

**Describe the bug**
TASK [qubinode_kvmhost_setup : copy qcow image to machine] **********************************
Wednesday 22 July 2020  15:10:36 +0800 (0:00:00.328)       0:00:28.637 ******** 
fatal: [localhost]: FAILED! => 
  reason: Could not find or access '/home/louie/qubinode-installer/playbooks/copy_qcow_image.yml' on the Ansible Controller.

Cannot find this playbook in the directory

**To Reproduce**
1. ./qubinode-installer -m host

**Expected behavior**
No failed msg.

**Comment by tosin2013** [comment]
The file https://github.com/Qubinode/qubinode_kvmhost_setup/blob/dev/tasks/copy_qcow_image.yml.  You should be able to rerun the qubinode-installer -m ansible again and the playbook should work.

**Comment by dingyeah33** [comment]
> The file https://github.com/Qubinode/qubinode_kvmhost_setup/blob/dev/tasks/copy_qcow_image.yml. You should be able to rerun the qubinode-installer -m ansible again and the playbook should work.

Yes, it fixed

**Comment by tosin2013** [comment]
This should be fixed in the v2.4.2 release 
https://github.com/Qubinode/qubinode-installer/commit/9c78a4458c66b562b28adf9d6ec3c4b9c7946138
