### ISSUE TITLE
[BUG]Error on creating the idm server

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#254]
**Qubinode Version**  
Qubinode releasev2.4.2

**Describe the bug**
TASK [ipaserver : Install - Server installation test] *****************************************************************************************
Wednesday 22 July 2020  22:30:54 +0800 (0:00:00.040)       0:02:39.658 ******** 
fatal: [qbn-dns01]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'idm_reverse' is undefined
  
    The error appears to be in '/home/louie/qubinode-installer/playbooks/roles/ipaserver/tasks/install.yml': line 46, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: Install - Server installation test
      ^ here

**To Reproduce**
1. ./qubinode-installer -p idm

**Expected behavior**
idm VM can be created

**Additional context**
I have added this statement "interpreter_python  = auto" in the ansible.cfg

**Comment by tosin2013** [comment]
This should be fixed in the v2.4.2 release 
https://github.com/Qubinode/qubinode-installer/commit/9c78a4458c66b562b28adf9d6ec3c4b9c7946138
