### ISSUE TITLE
Verify 3 node cluster deployment with ocp 4.5

### ISSUE THREAD

**Issue by flyemsafe** [Qubinode/qubinode-installer#268]
https://docs.openshift.com/container-platform/4.5/installing/installing_bare_metal/installing-bare-metal.html#installation-three-node-cluster_installing-bare-metal

**Comment by tosin2013** [comment]
This is a feature in the v2.4.2 release 
https://github.com/Qubinode/qubinode-installer/commit/9c78a4458c66b562b28adf9d6ec3c4b9c7946138
