### ISSUE TITLE
[BUG]IDM Server playbook fails because it's checking for Idm status before configuring resolv file

### ISSUE THREAD

**Issue by amalivert** [Qubinode/qubinode-installer#269]
**Qubinode Version**  
Qubinode dev branch

**Describe the bug**
Playbook run took 0 days, 0 hours, 12 minutes, 43 seconds
 IDM Server was not properly deployed please verify deployment.
[qubi@qubi-box qubinode-installer]$ ./qubinode-installer -p idm

Running IdM VM deploy function

   If you've made an mistake hit Ctrl-c to exit the install.
   Then run the below command to reset the installation.

   ./qubinode-installer -m clean

   Running ./qubinode-installer -m clean removes all configuration data.
   This effectively resets the installation progress.

     IdM server is installed
   ****************************************************
    Webconsole: https://qbn-dns01.lab.example/ipa/ui/ 
    IP Address: 192.168.86.114 
    Username: admin
    Password: the vault variable admin_user_password 

    Run: ansible-vault edit /home/qubi/qubinode-installer/playbooks/vars/vault.yml

**Comment by tosin2013** [comment]
This should be fixed in the v2.4.2 release 
https://github.com/Qubinode/qubinode-installer/commit/9c78a4458c66b562b28adf9d6ec3c4b9c7946138
