### ISSUE TITLE
remove copys of idm entrys in hosts file 

### ISSUE THREAD

**Issue by tosin2013** [Qubinode/qubinode-installer#27]
on each idm reinstall the hosts file still contains entries to the old server

example
192.168.1.x ocp-idm01 ocp-idm01.lab.testme
192.168.1.x ocp-idm01 ocp-idm01.lab.example

**Comment by flyemsafe** [comment]
@tosin2013 is this still an issue?

**Comment by tosin2013** [comment]
this has been fixed in a different repo 
https://github.com/tosin2013/ansible-role-rhel7-kvm-cloud-init/commit/98fa429fc1ac3f002bd2e0ff6c8026d2e31252be
