### ISSUE TITLE
[BUG]OCP4 cluster cannot startup

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#279]
**Qubinode Version**  
Qubinode releasev2.4.2

**Describe the bug**
Try to use ./qubinode-installer -p ocp4 -m startup, the OCP4 cluster cannot startup with the below error:

fatal: [localhost]: FAILED! => changed=false 
  attempts: 18
  cmd: |-
    /usr/local/bin/oc get nodes -o wide --no-headers=true | grep ctrlplane| grep Ready|wc -l
  delta: '0:00:00.189779'
  end: '2020-08-20 18:58:00.158341'
  rc: 0
  start: '2020-08-20 18:57:59.968562'
  stderr: 'error: You must be logged in to the server (Unauthorized)'
  stderr_lines: <omitted>
  stdout: '0'
  stdout_lines: <omitted>
...ignoring

TASK [ocp4_kvm_deployer : fail a total 3 is not found] *************************************************
Thursday 20 August 2020  18:58:00 +0800 (0:03:08.369)       0:03:14.715 ******* 
fatal: [localhost]: FAILED! => changed=false 
  msg: Was not able to confirm all 3 ctrlplane nodes are up

PLAY RECAP *********************************************************************************************
localhost                  : ok=10   changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=1   

Thursday 20 August 2020  18:58:00 +0800 (0:00:00.036)       0:03:14.752 ******* 
=============================================================================== 
ocp4_kvm_deployer : wait for ctrlplane nodes to be available ---------------------------------- 188.37s
Gathering Facts --------------------------------------------------------------------------------- 1.61s
ocp4_kvm_deployer : collect all services state -------------------------------------------------- 1.55s
ocp4_kvm_deployer : start ocp ctrlplane nodes --------------------------------------------------- 0.99s
ocp4_kvm_deployer : list all libvirt vms -------------------------------------------------------- 0.59s
ocp4_kvm_deployer : get qbn-lb container info --------------------------------------------------- 0.57s
ocp4_kvm_deployer : check if Loadbalancer SystemD service exists -------------------------------- 0.49s
ocp4_kvm_deployer : get users homedir ----------------------------------------------------------- 0.13s
ocp4_kvm_deployer : fail if the systemd service qbn-lb.service is not running ------------------- 0.10s
ocp4_kvm_deployer : set qbn-lb container state -------------------------------------------------- 0.08s
ocp4_kvm_deployer : set_fact -------------------------------------------------------------------- 0.08s
ocp4_kvm_deployer : start the loadbancer systemd service qbn-lb.service ------------------------- 0.06s
ocp4_kvm_deployer : fail a total 3 is not found ------------------------------------------------- 0.04s
Playbook run took 0 days, 0 hours, 3 minutes, 14 seconds

All 3 control-plane VMs had been startup and other 3 worker nodes are still in shutdown status

Try to use oc login -u kubeadmin, it come out the error "error: EOF" and cannot check any CSR status.

**To Reproduce**
1. ./qubinode-installer -p ocp4 -m shutdown
2. Shutdown the Linux host
3. Wait for overnight and start the linux host
4. ./qubiode-installer -p ocp4 -m startup

**Expected behavior**
OCP4 cluster should be startup without error

**Additional context**
If I shutdown and start the cluster within a short period, and the cluster can be startup without problem

**Comment by tosin2013** [comment]
We will test this issue.
