### ISSUE TITLE
[BUG] Documentation error

### ISSUE THREAD

**Issue by apitanga** [Qubinode/qubinode-installer#289]
**Qubinode Version**  
Documentation error

**Describe the bug**
On qubinode.io main page on the section entitled "The qubinode-installer" the download location is incorrect

**To Reproduce**
1. Got to qubinode.io
2. Follow the installation steps
3. Click on https://github.com/Qubinode/qubinode-installer/archive/main.zip

**Expected behavior**
Download succeeds

**Additional context**
Download link changed?

**Comment by tosin2013** [comment]
the documentation has been updated 
https://github.com/Qubinode/qubinode-installer/tree/master/docs
