### ISSUE TITLE
[BUG] ./qubinode-installer -m setup sed error

### ISSUE THREAD

**Issue by apitanga** [Qubinode/qubinode-installer#290]
**Qubinode Version**  
Latest

**Describe the bug**
`./qubinode-installer -m setup` returns an error: 

```sed: -e expression #1, char 42: unterminated `s' command```

**To Reproduce**
1. Run qubinode setup: `./qubinode-installer -m setup`

**Expected behavior**
Setup ends without error

**Comment by tosin2013** [comment]
This should be fixed in the dev branch 
https://github.com/Qubinode/qubinode-installer/commits/dev
