### ISSUE TITLE
[BUG]Error on checking NFS available disk size

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#305]
**Qubinode Version**  
Qubinode releasev2.4.2 - dev branch

**Describe the bug**

Configure the NFS mount point
fatal: [localhost]: FAILED! => changed=false 
  msg: The system may not create nfs server you do not have at least 300 GB mount.

**To Reproduce**
1. ./qubinode-installer -m host

**Expected behavior**
Should be configured without error

**Screenshots**
TASK [set nfs mount point fact] ************************************************************
Wednesday 25 November 2020  15:11:41 +0800 (0:00:00.067)       0:00:02.220 **** 
ok: [localhost] => (item={'mount': '/', 'device': '/dev/mapper/rhel-root', 'fstype': 'xfs', 'options': 'rw,seclabel,relatime,attr2,inode64,noquota', 'size_total': 473871659008, 'size_available': 462391312384, 'block_size': 4096, 'block_total': 115691323, 'block_available': 112888504, 'block_used': 2802819, 'inode_total': 231495680, 'inode_available': 231349632, 'inode_used': 146048, 'uuid': '40fc030d-4af4-43dc-aa47-9ae91959c0f8'})
skipping: [localhost] => (item={'mount': '/var/lib/libvirt/images', 'device': '/dev/mapper/vg_qubi-lv_qubi_images', 'fstype': 'xfs', 'options': 'rw,seclabel,relatime,attr2,inode64,noquota', 'size_total': 1999421038592, 'size_available': 1998228119552, 'block_size': 4096, 'block_total': 488139902, 'block_available': 487848662, 'block_used': 291240, 'inode_total': 195351296, 'inode_available': 195351292, 'inode_used': 4, 'uuid': '5c193a0d-3ed8-4c68-8ddb-d32e2cf48f19'}) 
skipping: [localhost] => (item={'mount': '/boot', 'device': '/dev/sda2', 'fstype': 'xfs', 'options': 'rw,seclabel,relatime,attr2,inode64,noquota', 'size_total': 1063256064, 'size_available': 743161856, 'block_size': 4096, 'block_total': 259584, 'block_available': 181436, 'block_used': 78148, 'inode_total': 524288, 'inode_available': 524201, 'inode_used': 87, 'uuid': '81085699-03bf-4b85-8ad4-3049560c66f3'}) 

TASK [checking if / is greater that 300 GB] ************************************************
Wednesday 25 November 2020  15:11:41 +0800 (0:00:00.093)       0:00:02.314 **** 
ok: [localhost] => 
  msg: Using mount /nfs_mount/data

TASK [check if item that is not / mount is greater than 300 GB] ****************************
Wednesday 25 November 2020  15:11:41 +0800 (0:00:00.074)       0:00:02.389 **** 
skipping: [localhost]

TASK [set directory location under /] ******************************************************
Wednesday 25 November 2020  15:11:41 +0800 (0:00:00.071)       0:00:02.460 **** 
fatal: [localhost]: FAILED! => 
  msg: |-
    The conditional check '(item.size_total / 1000000000) > 300.00 and  nfs_mount_point.mount == "/"' failed. The error was: error while evaluating conditional ((item.size_total / 1000000000) > 300.00 and  nfs_mount_point.mount == "/"): 'item' is undefined
  
    The error appears to be in '/home/louie/qubinode-installer/playbooks/configure-nfs.yml': line 33, column 5, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
      - name: set directory location under /
        ^ here
...ignoring

TASK [set directory location under /home if found] *****************************************
Wednesday 25 November 2020  15:11:41 +0800 (0:00:00.071)       0:00:02.532 **** 
skipping: [localhost]

TASK [fail when nfsmount point cannot be created] ******************************************
Wednesday 25 November 2020  15:11:41 +0800 (0:00:00.068)       0:00:02.600 **** 
fatal: [localhost]: FAILED! => changed=false 
  msg: The system may not create nfs server you do not have at least 300 GB mount.

PLAY RECAP *********************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=1   

Wednesday 25 November 2020  15:11:41 +0800 (0:00:00.046)       0:00:02.646 **** 
=============================================================================== 
Gathering Facts --------------------------------------------------------------------- 1.31s
Collect only facts about hardware --------------------------------------------------- 0.82s
set nfs mount point fact ------------------------------------------------------------ 0.09s
checking if / is greater that 300 GB ------------------------------------------------ 0.07s
check if item that is not / mount is greater than 300 GB ---------------------------- 0.07s
set directory location under / ------------------------------------------------------ 0.07s
set directory location under /home if found ----------------------------------------- 0.07s
Collecting xfs mounts --------------------------------------------------------------- 0.07s
fail when nfsmount point cannot be created ------------------------------------------ 0.05s
Playbook run took 0 days, 0 hours, 0 minutes, 2 seconds

**Additional context**
Output of "df -T"
Filesystem                         Type      1K-blocks     Used  Available Use% Mounted on
devtmpfs                           devtmpfs  264013436        0  264013436   0% /dev
tmpfs                              tmpfs     264041992        0  264041992   0% /dev/shm
tmpfs                              tmpfs     264041992    18728  264023264   1% /run
tmpfs                              tmpfs     264041992        0  264041992   0% /sys/fs/cgroup
/dev/mapper/rhel-root              xfs       462765292 11206084  451559208   3% /
/dev/mapper/vg_qubi-lv_qubi_images xfs      1952559608  1164960 1951394648   1% /var/lib/libvirt/images
/dev/sda2                          xfs         1038336   312592     725744  31% /boot
/dev/sda1                          vfat         613184     7024     606160   2% /boot/efi
tmpfs                              tmpfs      52808396       40   52808356   1% /run/user/1000

**Comment by tosin2013** [comment]
what does verbose give you `-vv`
`ansible-playbook playbooks/configure-nfs.yml -vv`

**Comment by dingyeah33** [comment]
Here is the verbose output
[configure-nfs.log](https://github.com/Qubinode/qubinode-installer/files/5610016/configure-nfs.log)

**Comment by dingyeah33** [comment]
It also has the same problem at v2.4.3
