### ISSUE TITLE
[BUG] Errors found in QBN-BOX log

### ISSUE THREAD

**Issue by wadebee** [Qubinode/qubinode-installer#319]
**Quibinode Version**  
Release 2.4.3

**Openshift Version**  
OpenShift v4.6.17

**Describe the bug**
Found two error message in QBN-BOX log immediately after upgrading to OS version 4.6.17. 

SELinux is preventing /usr/libexec/platform-python3.6 from getattr access on the file /usr/sbin/kpatch. For complete SELinux messages run: sealert -l 31aebc52-2a37-4770-bbfa-489f571121fc 

SELinux is preventing /usr/libexec/platform-python3.6 from node_bind access on the tcp_socket port None. For complete SELinux messages run: sealert -l f590459b-34f3-4e33-ae66-21e505f5e971

**To Reproduce**
1. Installed fresh copy of Qubinode
2. Log into OCP web console after successful install
3. OCP web console alerts to an available upgrade to OS v4.6.17
4. After successful upgrade saw these two errors in the QBN-BOX logs

**Expected behavior**
Didn't expect to see these errors. They may be harmless but wanted to report them in case they are a real problem.

**Screenshots**

**Additional context**
Additional details from logging error#1:

SYSLOG_IDENTIFIER | setroubleshoot
-- | --
_BOOT_ID | 38b7c3bb7e61417983f0c07b457629c4
_CAP_EFFECTIVE | 0
_CMDLINE | /usr/libexec/platform-python -Es /usr/sbin/setroubleshootd -f
_COMM | setroubleshootd
_EXE | /usr/libexec/platform-python3.6
_GID | 984
_HOSTNAME | qbn-box-785f.lab.qubinode.io
_MACHINE_ID | 60472573ef4c44b999c15dcf215a5a6f
_PID | 1169157
_SELINUX_CONTEXT | system_u:system_r:setroubleshootd_t:s0-s0:c0.c1023
_SOURCE_REALTIME_TIMESTAMP | 1613957280755350
_SYSTEMD_CGROUP | /system.slice/dbus.service
_SYSTEMD_INVOCATION_ID | 33f3309dd7db445d875ead456b627cab
_SYSTEMD_SLICE | system.slice
_SYSTEMD_UNIT | dbus.service
_TRANSPORT | syslog
_UID | 991
__CURSOR | s=5c514a52edd645c0b7b43a27748a393d;i=22cb0;b=38b7c3bb7e61417983f0c07b457629c4;m=1cc0cb6818;t=5bbe2b666eea8;x=e353dd8ab9cfd2d4
__MONOTONIC_TIMESTAMP | 123493640216
__REALTIME_TIMESTAMP | 1613957280755368

Additional details from logging error#2:
PRIORITY | 3
-- | --
SYSLOG_FACILITY | 1
SYSLOG_IDENTIFIER | setroubleshoot
_BOOT_ID | 38b7c3bb7e61417983f0c07b457629c4
_CAP_EFFECTIVE | 0
_CMDLINE | /usr/libexec/platform-python -Es /usr/sbin/setroubleshootd -f
_COMM | setroubleshootd
_EXE | /usr/libexec/platform-python3.6
_GID | 984
_HOSTNAME | qbn-box-785f.lab.qubinode.io
_MACHINE_ID | 60472573ef4c44b999c15dcf215a5a6f
_PID | 1169157
_SELINUX_CONTEXT | system_u:system_r:setroubleshootd_t:s0-s0:c0.c1023
_SOURCE_REALTIME_TIMESTAMP | 1613957277856164
_SYSTEMD_CGROUP | /system.slice/dbus.service
_SYSTEMD_INVOCATION_ID | 33f3309dd7db445d875ead456b627cab
_SYSTEMD_SLICE | system.slice
_SYSTEMD_UNIT | dbus.service
_TRANSPORT | syslog
_UID | 991
__CURSOR | s=5c514a52edd645c0b7b43a27748a393d;i=22ca8;b=38b7c3bb7e61417983f0c07b457629c4;m=1cc09f2b2a;t=5bbe2b63ab1b9;x=dd05084639ea0b26
__MONOTONIC_TIMESTAMP | 123490741034
__REALTIME_TIMESTAMP | 1613957277856185

**Hardware Profile infomation**  
Please paste the result of the script found under lib//qubinode_hardware_profile.sh  
If script is not on your machine use the following link [lib/qubinode_hardware_profile.sh](https://github.com/Qubinode/qubinode-installer/blob/post_release/lib/qubinode_hardware_profile.sh)

**Comment by flyemsafe** [comment]
Closing this issue for now since it does not appear to break any functionality with the Qubinode.
