### ISSUE TITLE
[BUG] deployment of nfs-provisioner-client should wait for image-registry operator to be available

### ISSUE THREAD

**Issue by flyemsafe** [Qubinode/qubinode-installer#332]
Ensure image-registry AVAILABLE status is true before completing the deployment.

```
image-registry                             4.7.0     False       True          True       5m43s
```

**Comment by tosin2013** [comment]
This has been fixed with the new nfs-provisoner code 
https://github.com/Qubinode/qubinode-installer/tree/v2.4.5
