### ISSUE TITLE
The task includes an option with an undefined variable. The error was: 'idm_admin_password'

### ISSUE THREAD

**Issue by amalivert** [Qubinode/qubinode-installer#34]
TASK [ansible-idm : Run the installer] ***********************************************************************************************
Sunday 18 August 2019  18:00:17 -0400 (0:00:00.931)       0:04:44.885 ********* 
fatal: [ocp-dns01]: FAILED! => {
    "changed": true, 
    "cmd": "/root/ipa-srv-install.sh", 
    "delta": "0:00:00.752838", 
    "end": "2019-08-18 18:00:19.091466", 
    "rc": 2, 
    "start": "2019-08-18 18:00:18.338628"
}

STDERR:

ipapython.install.cli: DEBUG    Logging to /var/log/ipaserver-install.log
Usage: ipa-server-install [options]

ipa-server-install: error: option admin-password: Password must be at least 8 characters long
ipapython.admintool: DEBUG      File "/usr/lib/python2.7/site-packages/ipapython/admintool.py", line 178, in execute
    return_value = self.run()
  File "/usr/lib/python2.7/site-packages/ipapython/install/cli.py", line 310, in run
    self.option_parser.error("{0}: {1}".format(desc, e))
  File "/usr/lib64/python2.7/optparse.py", line 1583, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/usr/lib64/python2.7/optparse.py", line 1573, in exit
    sys.exit(status)

ipapython.admintool: DEBUG    The ipa-server-install command failed, exception: SystemExit: 2
ipapython.admintool: ERROR    The ipa-server-install command failed.

MSG:

non-zero return code

**Comment by flyemsafe** [comment]
@amalivert is this still an issue?

**Comment by tosin2013** [comment]
this should have been fixed please test with https://github.com/Qubinode/qubinode-installer/releases/tag/2.3.1 release
