### ISSUE TITLE
[BUG]system is registered with no subscription attached

### ISSUE THREAD

**Issue by amalivert** [Qubinode/qubinode-installer#348]
I am using my developer account

 ****************************************************************************
            Red Hat Subscription Registration

   Your credentials for access.redhat.com is needed.

   This is use to register this instance of RHEL and
   along with the other RHEL vms that will be deployed.

   There are two types of credentials:
     (*) activation key
     (*) username/password

   The username/password is what's more commonly use.
   The activation key is commonly use with a Satellite server.

   Which option are you using to register the system?
1) Activation Key
2) Username and Password
#? 1
   Enter your RHSM activation key and press [ENTER]: amkey
   Enter your RHSM ORG ID and press [ENTER]: ********

  Registering system to rhsm using your activaiton key.
 qubox.localdomain registration to RHSM was unsuccessfull.
The system has been registered with ID: b82e819c-a18d-4e2e-99cd-a374bf65419d
The registered system name is: qubox.localdomain
Installed Product Current Status:
Product Name: Red Hat Enterprise Linux for x86_64
Status:       Not Subscribed

Unable to find available subscriptions for all your installed products.

**Comment by flyemsafe** [comment]
What is the output of these commands?

```
subscription-manager list --available --all
```

```
subscription-manager list --consumed
```

```
subscription-manager status
```

**Comment by amalivert** [comment]
sorry @flyemsafe I manually attached subscriptions to it already ... I am planning on reimaging and start from scratch

**Comment by amalivert** [comment]
@flyemsafe it worked today .. must have been something with Red Hat
