### ISSUE TITLE
[BUG] qubinode current release rhsm_token does not work

### ISSUE THREAD

**Issue by amalivert** [Qubinode/qubinode-installer#360]
the rhsm token option to register server does not work like it should and fails with :

Did not find rhel-8.3-update-2-x86_64-kvm.qcow2 in path /home/admin/qubinode-installer.
 Download and copy rhel-8.3-update-2-x86_64-kvm.qcow2 to /home/admin/qubinode-installer.

**Comment by flyemsafe** [comment]
This fix is targeted for the 3.0 release. The documentation reference to this step should be removed.
