### ISSUE TITLE
[BUG] update code to include ocp token

### ISSUE THREAD

**Issue by amalivert** [Qubinode/qubinode-installer#365]
██    ██ ██    ██ ██████  ██ ██ ██  ██ ██    ██ ██   ██ █████   
     ██ ▄▄ ██ ██    ██ ██   ██ ██ ██  ██ ██ ██    ██ ██   ██ ██      
      ██████   ██████  ██████  ██ ██   ████  ██████  ██████  ███████ 
         ▀▀                                                          

  ****************************************************************************
        Red Hat Openshift Container Platform 4 (OCP4)

    The default product option is to install OCP4. The deployment consists of
    3 ctrlplane and 3 computes. It requires a minimum of 96 Gib memory and 8 cores.
    Each node is deployed with 16 Gib memory and 4 vCPUs with NFS for persistent
    storage. If you don't meet these requirements exit the install and run
    ./qubinode-installer -p ocp4 for options to deploy a smaller cluster.

    **The installer also requires your OpenShift pull-secret. Please refer to
    the documentation for info on obtaining your pull secret.**

  ****************************************************************************

**Comment by flyemsafe** [comment]
This will be addressed in the planned 3.0 release.
