### ISSUE TITLE
cannot create regular file ‘/var/lib/libvirt/images/rhel-server-7.6-x86_64-kvm.qcow2’

### ISSUE THREAD

**Issue by tosin2013** [Qubinode/qubinode-installer#37]
Enter your RHSM username and press [ENTER]: example@example.com
Enter your RHSM password and press [ENTER]: ********************
cp: cannot create regular file ‘/var/lib/libvirt/images/rhel-server-7.6-x86_64-kvm.qcow2

The ‘/var/lib/libvirt/images/ does not exist until the secondary harddrive is formated and folder is created.

**Comment by flyemsafe** [comment]
@tosin2013 is this still an issue?
