### ISSUE TITLE
[BUG]fatal: ./qubinode-installer -m deploy fails

### ISSUE THREAD

**Issue by amalivert** [Qubinode/qubinode-installer#39]
TASK [ansible-role-rhel7-kvm-cloud-init : get vm gateway from DHCP server]  fails with the following:

fatal: [localhost]: UNREACHABLE! => {
    "changed": false, 
    "unreachable": true
}

MSG:

Failed to connect to the host via ssh: key_load_public: invalid format
Warning: Permanently added '192.168.1.90' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

**Comment by flyemsafe** [comment]
fixed 2ca083c5930f4b97380a75bac301b99b35d13ef4
