### ISSUE TITLE
When is another release coming?

### ISSUE THREAD

**Issue by TechnoRoss** [Qubinode/qubinode-installer#418]
From what I've seen here, the last release was v2.4.6, September 2021.  However, I see development activity within the last week or two, so I know activity is ongoing. 

The README even indicates the latest release:
Qubinode Version | Ansible version | Tag
-- | -- | --
Release 3.0 | 2.10 | 2.8.0

However, there is not a tag associated, or a corresponding zip.  The upshot is I want to deploy an OKD 4 cluster, but it appears the last time you included the ansible files & instructions was about 18 months ago.

Any insights?  Installing Openshift OKD should not be as difficult as it has turned out to be in my last few days.  This repo gave me hope, only to come up short as many others have.  The article that led me here is: https://medium.com/@tcij1013/installing-okd-the-community-distribution-of-kubernetes-4-x-cluster-on-a-single-node-8410146858b6

**Comment by tosin2013** [comment]
There will be a release coming out soon. I also need to check the release with OKD before I make a final one. I am currently working on getting OPenShift 4.11 working https://qubinode-installer.readthedocs.io/en/latest/ocp4-ai-svc-universal.html.

**Comment by TechnoRoss** [comment]
Thanks! looking forward to it!
