### ISSUE TITLE
[BUG] SSH keyname is incorrect 

### ISSUE THREAD

**Issue by tosin2013** [Qubinode/qubinode-installer#42]
**Describe the bug**

**To Reproduce**
1. ./qubinode-installer -m deploy_dns

**Expected behavior**

**Screenshots**
$ ls ~/.ssh/
id_rsa.pub  id_rsa.pub.pub  known_hosts

TASK [ansible-role-rhel7-kvm-cloud-init : get vm gateway from DHCP server] ************************************************************************************
Friday 23 August 2019  17:40:49 -0400 (0:00:00.390)       0:01:09.906 ********* 
fatal: [localhost]: UNREACHABLE! => {
    "changed": false, 
    "unreachable": true
}

MSG:

Failed to connect to the host via ssh: key_load_public: invalid format
Warning: Permanently added '192.168.1.125' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

**Additional context**

**Comment by flyemsafe** [comment]
@tosin2013 please verify and close.

**Comment by flyemsafe** [comment]
fixed 2ca083c5930f4b97380a75bac301b99b35d13ef4
