### ISSUE TITLE
[BUG] -swygue-redhat-subscription : these repos will be enabled 

### ISSUE THREAD

**Issue by tosin2013** [Qubinode/qubinode-installer#43]
**Describe the bug**

**To Reproduce**
1. ./qubinode-installer -m deploy_dns

**Expected behavior**
the dns to active the correct repos for idm

**Screenshots**
TASK [swygue-redhat-subscription : these repos will be enabled] ***********************************************************************************************
Friday 23 August 2019  17:44:06 -0400 (0:00:00.025)       0:00:16.566 ********* 
fatal: [ocp-dns01]: FAILED! => {}

MSG:

The conditional check 'repos_to_enable|length > 0' failed. The error was: Unexpected templating type error occurred on ({% if repos_to_enable|length > 0 %} True {% else %} False {% endif %}): object of type 'bool' has no len()

The error appears to have been in '/home/admin/qubinode-installer/playbooks/roles/swygue-redhat-subscription/tasks/repos.yml': line 44, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: these repos will be enabled
  ^ here

**Additional context**

**Comment by flyemsafe** [comment]
fixed in https://github.com/flyemsafe/swygue-redhat-subscription/commit/91f6796dc6f1ffbe18a431259cd63b95e371855f @tosin2013 please verify and close issue.

**Comment by tosin2013** [comment]
This has been fixed
