### ISSUE TITLE
No package matching 'cockpit-packagekit' found available, installed or updated

### ISSUE THREAD

**Issue by tosin2013** [Qubinode/qubinode-installer#5]
TASK [swygue.edge_host_setup : ensure libvirt packages are installed] *****************************************************************************************
Tuesday 06 August 2019  19:28:45 -0400 (0:00:00.043)       0:00:01.738 ******** 
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "rc": 126, 
    "results": [
        "No package matching 'cockpit-packagekit' found available, installed or updated"
    ]
}

MSG:

No package matching 'cockpit-packagekit' found available, installed or updated

PLAY RECAP ****************************************************************************************************************************************************
localhost               

**The fix is yum-config-manager --enable rhel-7-server-extras-rpms**

**Comment by flyemsafe** [comment]
you need to enable the rhel-7-server-extras-rpms repo. I will add some code to check for this and enable it if it's not there.

**Comment by tosin2013** [comment]
Fixed in https://github.com/tosin2013/openshift-home-lab/commit/89fc02b54f2e67b76c47804921055b21ac07d9bb
