### ISSUE TITLE
[BUG] delete PTR Records out of dns on delete

### ISSUE THREAD

**Issue by tosin2013** [Qubinode/qubinode-installer#52]
**Describe the bug**

**To Reproduce**
1.  run ./qubinode-installer -m deploy_nodes -p ocp -d

**Expected behavior**
PTR nodes are removed from DNS server

**Screenshots**
POINTER Nodes still exist in dnsserver

**Comment by tosin2013** [comment]
work around manually remove the ptr records from the dnsserver

**Comment by flyemsafe** [comment]
fixed commit c184cadabb706ceff0f7a305ab9fb99f086ccbd8
