### ISSUE TITLE
[BUG] swygue.edge_host_setup : setup bridge interface

### ISSUE THREAD

**Issue by tosin2013** [Qubinode/qubinode-installer#53]
**Describe the bug**

**To Reproduce**
1../qubinode-installer -m host -p ocp

**Expected behavior**
complete without failures

**Screenshots**
TASK [swygue.edge_host_setup : setup bridge interface] ********************************************************************************************************
Saturday 31 August 2019  11:29:13 -0400 (0:00:00.277)       0:50:23.561 ******* 
failed: [localhost] (item={u'bridge': u'qubibr0', u'name': u'qubinet', u'mode': u'bridge'}) => {
    "changed": false, 
    "item": {
        "bridge": "qubibr0", 
        "mode": "bridge", 
        "name": "qubinet"
    }
}

MSG:

AnsibleUndefinedVariable: 'kvm_host_ipaddr' is undefined

PLAY RECAP ****************************************************************************************************************************************************
localhost                  : ok=45   changed=13   unreachable=0    failed=1   

**Additional context**

**Comment by flyemsafe** [comment]
for now just add to playbooks/vars/all.yml

```
kvm_host_ipaddr: "{{ kvm_host_ip }}"
```

**Comment by tosin2013** [comment]
This has been fixed with the verify variables playbook https://github.com/Qubinode/swygue.edge_host_setup/blob/master/tasks/verify_variables.yml
