### ISSUE TITLE
Getting Failure message when installing cockpit 

### ISSUE THREAD

**Issue by tosin2013** [Qubinode/qubinode-installer#6]
Installed: Red Hat Enterprise Linux Server release 7.6 (Maipo)
enabled the yum-config-manager --enable rhel-7-server-extras-rpms
ran the ./start_deployment.sh -k setup

TASK [swygue.edge_host_setup : ensure libvirt packages are installed] *****************************************************************************************
Wednesday 07 August 2019  16:13:32 -0400 (0:00:00.042)       0:00:01.805 ****** 
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "changes": {
        "installed": [
            "virt-install", 
            "libvirt-daemon-config-network", 
            "libvirt-daemon-kvm", 
            "qemu-kvm", 
            "nfs-utils", 
            "libvirt-daemon", 
            "libvirt-client", 
            "virt-top", 
            "cockpit-bridge", 
            "cockpit-networkmanager", 
            "cockpit-packagekit", 
            "cockpit-shell", 
            "cockpit-storaged", 
            "cockpit-ws", 
            "cockpit-kubernetes", 
            "cockpit-pcp"
        ]
    }, 
    "rc": 1, 

....
MSG:

Error: Package: cockpit-shell-126-1.el7.noarch (rhel-7-server-extras-rpms)
           Requires: cockpit-bridge = 126-1.el7
           Available: cockpit-bridge-0.53-3.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.53-3.el7
           Available: cockpit-bridge-0.58-2.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.58-2.el7
           Available: cockpit-bridge-0.63-1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.63-1.el7
           Available: cockpit-bridge-0.71-1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.71-1.el7
           Available: cockpit-bridge-0.77-3.1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.77-3.1.el7
           Available: cockpit-bridge-0.93-3.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.93-3.el7
           Available: cockpit-bridge-0.96-2.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.96-2.el7
           Available: cockpit-bridge-0.103-1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.103-1.el7
           Available: cockpit-bridge-0.108-1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.108-1.el7
           Available: cockpit-bridge-0.114-2.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.114-2.el7
           Available: cockpit-bridge-118-2.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 118-2.el7
           Available: cockpit-bridge-122-3.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 122-3.el7
           Available: cockpit-bridge-126-1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 126-1.el7
           Available: cockpit-bridge-131-3.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 131-3.el7
           Available: cockpit-bridge-135-4.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 135-4.el7
           Available: cockpit-bridge-138-6.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 138-6.el7
           Available: cockpit-bridge-138-9.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 138-9.el7
           Available: cockpit-bridge-138-10.el7_4.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 138-10.el7_4
           Available: cockpit-bridge-154-3.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 154-3.el7
           Available: cockpit-bridge-173-7.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 173-7.el7
           Available: cockpit-bridge-173.1-1.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 173.1-1.el7
           Available: cockpit-bridge-173.2-1.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 173.2-1.el7
           Installing: cockpit-bridge-195.1-1.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 195.1-1.el7
Error: Package: cockpit-shell-0.63-1.el7.noarch (rhel-7-server-extras-rpms)
           Requires: cockpit-bridge = 0.63-1.el7
           Available: cockpit-bridge-0.53-3.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.53-3.el7
           Available: cockpit-bridge-0.58-2.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.58-2.el7
           Available: cockpit-bridge-0.63-1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.63-1.el7
           Available: cockpit-bridge-0.71-1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.71-1.el7
           Available: cockpit-bridge-0.77-3.1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.77-3.1.el7
           Available: cockpit-bridge-0.93-3.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.93-3.el7
           Available: cockpit-bridge-0.96-2.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.96-2.el7
           Available: cockpit-bridge-0.103-1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.103-1.el7
           Available: cockpit-bridge-0.108-1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.108-1.el7
           Available: cockpit-bridge-0.114-2.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 0.114-2.el7
           Available: cockpit-bridge-118-2.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 118-2.el7
           Available: cockpit-bridge-122-3.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 122-3.el7
           Available: cockpit-bridge-126-1.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 126-1.el7
           Available: cockpit-bridge-131-3.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 131-3.el7
           Available: cockpit-bridge-135-4.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 135-4.el7
           Available: cockpit-bridge-138-6.el7.x86_64 (rhel-7-server-extras-rpms)
               cockpit-bridge = 138-6.el7
           Available: cockpit-bridge-138-9.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 138-9.el7
           Available: cockpit-bridge-138-10.el7_4.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 138-10.el7_4
           Available: cockpit-bridge-154-3.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 154-3.el7
           Available: cockpit-bridge-173-7.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 173-7.el7
           Available: cockpit-bridge-173.1-1.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 173.1-1.el7
           Available: cockpit-bridge-173.2-1.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 173.2-1.el7
           Installing: cockpit-bridge-195.1-1.el7.x86_64 (rhel-7-server-rpms)
               cockpit-bridge = 195.1-1.el7

**Comment by flyemsafe** [comment]
This was fixed

**Comment by flyemsafe** [comment]
This seem to be caused by the cockpit-kubernetes package. I removed it from the package list. commit # 397ce5fb3b29c02702f80830b5896bda8fc85ed3
