### ISSUE TITLE
[BUG] qubinode-installer prompts for openshift console

### ISSUE THREAD

**Issue by flyemsafe** [Qubinode/qubinode-installer#61]
**Describe the bug**
When running the qubinode-installer function **qubinode_deploy_openshift** your prompted to enter the openshift console user password.

**To Reproduce**
```
qubinode-installer -p ocp 
```

**Expected behavior**
No prompt for password

**Screenshots**

```
***************************************
Enter pasword to be used by qubinode user to access openshift console
***************************************
New password: 
```

**Additional context**

The qubinode-installer already collects the users password and stored it in the vault.yml user running the qubibode-installer should be created and the openshift console admin user along with the password collected.

**Comment by tosin2013** [comment]
This has been fixed openshift 3 console for uses the same ssh password as the qubinode box 
https://github.com/Qubinode/qubinode-installer/releases/tag/2.3.1
