### ISSUE TITLE
[BUG] deploy-kvm-vm fails at tasks Push base image onto vm operating system disk 

### ISSUE THREAD

**Issue by amalivert** [Qubinode/qubinode-installer#78]
**Describe the bug**
/home/qubi/qubinode-installer/lib/qubinode_hardware_check.sh: line 29: [[: 51179.5: syntax error: invalid arithmetic operator (error token is ".5")
/home/qubi/qubinode-installer/lib/qubinode_hardware_check.sh: line 32: [[: 51179.5: syntax error: invalid arithmetic operator (error token is ".5")
Your available storage of 49.98 GiB does not meet the requirements.
****
./qubinode-installer

**Comment by amalivert** [comment]
libguestfs-tools was not installed  on the host although it's part of required packages under vars/all.yml

**Comment by tosin2013** [comment]
https://github.com/Qubinode/qubinode-installer/releases/tag/2.3.1
