### ISSUE TITLE
[BUG]"oc login" cannot not find the oauth server at ocp4

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#79]
**Describe the bug**
Having installed ocp4 using v2.2 installer, try to use "oc login", it return this error:

error: dial tcp: lookup oauth-openshift.apps.ocp42.lab.example on 192.168.1.78:53: no such host

**Additional context**
Try to use this command "dig -x 192.168.1.78"

`; <<>> DiG 9.11.4-P2-RedHat-9.11.4-13.P2.el7 <<>> -x 192.168.1.78
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31086
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;78.1.168.192.in-addr.arpa. IN PTR

;; ANSWER SECTION:
78.1.168.192.in-addr.arpa. 86400 IN PTR qbn-dns01.lab.example.

;; AUTHORITY SECTION:
1.168.192.in-addr.arpa. 86400 IN NS qbn-dns01.lab.example.

;; ADDITIONAL SECTION:
qbn-dns01.lab.example. 1200 IN A 192.168.1.78

;; Query time: 0 msec
;; SERVER: 192.168.1.78#53(192.168.1.78)
;; WHEN: Thu Jan 02 13:15:01 HKT 2020
;; MSG SIZE rcvd: 119

[louie@peakone qubinode-installer]$ dig -x lab.example

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-13.P2.el7 <<>> -x lab.example
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 29285
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;example.lab.in-addr.arpa. IN PTR

;; AUTHORITY SECTION:
in-addr.arpa. 1871 IN SOA b.in-addr-servers.arpa. nstld.iana.org. 2019121765 1800 900 604800 3600

;; Query time: 42 msec
;; SERVER: 192.168.1.78#53(192.168.1.78)
;; WHEN: Thu Jan 02 13:17:31 HKT 2020
;; MSG SIZE rcvd: 121
`

**Comment by tosin2013** [comment]
This should be fixed with commit https://github.com/Qubinode/qubinode-installer/commit/929b1e74bb2e731fd3677633f474fc9e2d63698a
