### ISSUE TITLE
[BUG]Disk size calculation is wrong

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#80]
**Describe the bug**
Deploy either ocp3 or ocp4, it prompt out the system  do not have enough disk available, even it has 2T free size being available.

My disk is a U2 SSD which is recognised as NVME SSD in the OS

I use the git clone:
https://github.com/Qubinode/qubinode-installer.git

**Screenshots**
![image](https://user-images.githubusercontent.com/6370369/71699065-dd876a00-2df8-11ea-9336-41559468f06f.png)

df -k output and it only use 1% of the disk

![image](https://user-images.githubusercontent.com/6370369/71699103-090a5480-2df9-11ea-852f-d89c40573410.png)

**Comment by flyemsafe** [comment]
This should be fixed in the latest soon to be available branch called apple. It's targetted release 2.3 which should be available early Jan 2020.
