### ISSUE TITLE
[BUG]Deploy ocp3 with performance cluster option

### ISSUE THREAD

**Issue by dingyeah33** [Qubinode/qubinode-installer#83]
**Describe the bug**
I use the advance option to deploy ocp3 cluster, and I choose the option for "Performance Cluster" option for the CLI "./qubinode-installer -m deploy_nodes"

Having deployed the nodes, I run the CLI "./qubinode-installer -p ocp3", it aborted with the msg.:

_A performance cluster requires 8 nodes.
Was only able to verify connectivity to 6 nodes._

It seem the installer only create for 6 nodes instead of 8 nodes for performance cluster option

**Screenshots**
1. ./qubinode-installer -m deploy_nodes
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/6370369/71706339-23572900-2e1f-11ea-99b3-8b57ed6a3fc2.png">

2. ./qubinode-installer -p ocp3
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/6370369/71706353-3e299d80-2e1f-11ea-8297-c423b09254f6.png">

**Comment by flyemsafe** [comment]
This is fixed and will land in a soon to be available branch called apple. It's targetted release 2.3 which should be available early Jan 2020.
